### ISSUE TITLE
Notifications crash the app (2.4)

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhab-android#1090]
### Actual behaviour
Notifications received crash and close the app

### Expected behaviour
Receive Notification

 
### Steps to reproduce
1. Generate a notification from openhab
2. Use a list for it

#### Client
* Android version: Oreo
* Device model: Samsung S8
* Stock or customized ROM: Stock
* App version : 2.4
* Build flavor :  Play Store
* Device language: Hebrew

#### Server
* Server version: 2.4M5
* Reverse Proxy: 
* Authentication method : user and password

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by mueller-ma** [comment]
@gargamelonly Does this happen at every notification?

**Comment by gargamelonly** [comment]
How do I rollback to the previous app version?

**Comment by maniac103** [comment]
You can't, at least not without anyone providing the old version.
You don't have ADB installed on your PC by chance, do you?

**Comment by maniac103** [comment]
And I assume this happens only with real notifications, not with test notifications sent via the web frontend?

**Comment by gargamelonly** [comment]
What does it mean "notifications sent via web frontend" ?
I can get ADB but phone is not rooted.

**Comment by maniac103** [comment]
> What does it mean "notifications sent via web frontend" ?

I meant the test notifications one can send via myopenhab.org -> Options -> Devices.

> I can get ADB but phone is not rooted.

ADB is totally sufficient, root not needed. If you could reproduce the crash, run `adb logcat -b crash` on your PC and post the output here, that would be great.

**Comment by gargamelonly** [comment]
Not very familiar with how to get a log from ADB when the app crashes.
Could you please provide more guidance on how to get it? I Tried running the app and crashing it while ADB is connected and running the command you requested. I only got a "-wating for device-" and nothing more.

**Comment by mueller-ma** [comment]
You need to enable ADB in the Android settings developer options first. If you dont see the dev options, go to Android settings => Info and tab on the build number a few times until a toast shows up and says that you're a dev now.

**Comment by gargamelonly** [comment]
Did that.


בתאריך יום ד׳, 14 בנוב׳ 2018, 19:00, מאת mueller-ma <
notifications@github.com>:

**Comment by gargamelonly** [comment]
I see the device listed (unauthorized)

**Comment by mueller-ma** [comment]
Check your phone. There should be a dialog asking for adb access. If that's not there, switch between the usb modes (loading only, transfer files).

**Comment by gargamelonly** [comment]
Does this help:

11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: Process: org.openhab.habdroid, PID: 5582
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: java.util.UnknownFormatConversionException: Conversion = 'End of String'
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2641)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2602)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.Formatter.parse(Formatter.java:2557)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2504)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2458)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.lang.String.format(String.java:2814)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:505)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at org.openhab.habdroid.core.GcmMessageListenerService.makeNotification(GcmMessageListenerService.java:139)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at org.openhab.habdroid.core.GcmMessageListenerService.onMessageReceived(GcmMessageListenerService.java:79)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at com.google.android.gms.gcm.GcmListenerService.handleIntent(Unknown Source:251)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at com.google.android.gms.iid.zzg.run(Unknown Source:26)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-14 20:47:56.121 10348  5582  8698 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

**Comment by gargamelonly** [comment]
`11-14 20:47:56.326  1000  5005  9308 W ActivityManager: crash : org.openhab.habdroid,0
11-14 20:47:56.332  1000  5005  9308 W ActivityManager:   Force finishing activity org.openhab.habdroid/.ui.MainActivity
11-14 20:47:56.334  1000  5005  9308 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{80c9127d0 #16063 A=org.openhab.habdroid U=0 StackId=1 sz=1}, rootActivity=null
11-14 20:47:56.335  1000  5005  5005 D MdnieScenarioControlService: Listener Real Multi Window State : true
11-14 20:47:56.335  1000  5005  5005 D CodecSolution: MultiWindowEventListener::onMultiWindowFocusChanged(0)
11-14 20:47:56.335  1000  5005  5005 D CS_HdrController: MultiWindowEventListener::onFocusStackChanged(0)
11-14 20:47:56.338 10014  7535 16602 I TrayUsageStatesWatcher: notePauseComponent : ComponentInfo{org.openhab.habdroid/org.openhab.habdroid.ui.MainActivity}
11-14 20:47:56.340 10348  5582  5582 D MainActivity: onPause()
11-14 20:47:56.341 10348  5582  5582 D WidgetListFragment: onPause() https://192.168.1.108:8443/rest/sitemaps/home/0400, isAdded: true
11-14 20:47:56.342   nfc  5934  7439 I NfcService: setForegroundDispatch disable
11-14 20:47:56.357  1000  5005  5054 I ActivityManager: Showing crash dialog for package org.openhab.habdroid u0`

**Comment by gargamelonly** [comment]
@mueller-ma 
I have a clue for you :)
Changed phone language to English and Notifications are working as expected.
Now I understand why no one was reporting the same issue as it is probably related only to RTL language or specifically Hebrew translation of the app.

**Comment by maniac103** [comment]
Thanks for that log. Root cause is that the hebrew translation is broken the number placeholder is swapped. See https://github.com/openhab/openhab-android/blob/2.4.0-release/mobile/src/full/res/values-iw/strings.xml#L11-L16 ... `d%` should be `%d`.

@mueller-ma In Crowdin UI it looks like expected:
![grafik](https://user-images.githubusercontent.com/781373/48539096-7f2abf80-e8b6-11e8-9cdf-5d75543b3261.png)
Might this be an export issue?

**Comment by mueller-ma** [comment]
I contacted the crowdin support. Let's see what they answer

**Comment by mueller-ma** [comment]
They send me the following link: https://support.crowdin.com/online-editor/#translating-rtl-languages
I've done that for the Hebrew translation, but I'll ask the support if they can a safe guard against such an issue.

**Comment by mueller-ma** [comment]
@gargamelonly I published a new beta version (2.4.2) to the play store. Can you check if the app still crashes?

**Comment by gargamelonly** [comment]
No notifications at all now.

**Comment by gargamelonly** [comment]
Question:
Not related to this bug. In the App settings there is a Notification or Alert menu to select Notification sound and vibration, seems it has not affect on notification sound/vibration. 
Moreover, in Crowdin the %d should indicate the number of Notifications, I did not notice it is being used, multiple notifications appear in "serial" mode, never more than a single one.

**Comment by maniac103** [comment]
For the latter question: we create a summary notification, but showing it is up to the system UI'a discretion. Maybe Samsung's UI doesn't show it or only under certain circumstances.
Sound and vibration should be set in the notification settings for the app (long press the notification to get there) @mueller-ma We probably should hide the sound and vibration prefs on Oreo and higher.

**Comment by gargamelonly** [comment]
Thank you guys for the hard work and for the responsiveness!

**Comment by gargamelonly** [comment]
Another possible side effect to Notifications:
Notifications pop up only after the phone is manually awake.
Seems the app is not power efficient anymore so the automatic power saver puts the app into "deep sleep" mode.

**Comment by maniac103** [comment]
> Seems the app is not power efficient anymore

What is that supposed to mean? The service posting the notifications is triggered by a GCM notification, which is supposed to make the service a foreground service (see here https://developer.android.com/about/versions/oreo/background - search for 'FCM'). I wonder what's going on there, but it's hard to test without owning a Samsung phone myself.

**Comment by gargamelonly** [comment]
Sorry for my lack of knowledge in Android OS, I am a Hardware guy :)
I was just pointing out a difference in behavior compared to the previous app version 2.2 (I think) where notifications were received immediately after dispatching.

**Comment by mueller-ma** [comment]
> We probably should hide the sound and vibration prefs on Oreo and higher.

Yes, I'll propose a PR.

> I wonder what's going on there, but it's hard to test without owning a Samsung phone myself.

Samsung has a feature called "Monitored apps" (https://www.tech-recipes.com/rx/59391/use-app-power-monitor-samsung-galaxy-note7/) that kills all apps with high battery usage. That could be related to #833. I've seen that this feature also kills the Signal messenger that also uses GCM/FCM.
@gargamelonly Can you add openHAB to the whitelist ("unmonitored apps", see link above)? This should fix the issue.
