### ISSUE TITLE
Crash on Android 4

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1253]
````
Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)
       at org.openhab.habdroid.core.connection.ConnectionFactory.<init>(ConnectionFactory.java:121)
       at org.openhab.habdroid.core.connection.ConnectionFactory.initialize(ConnectionFactory.java:136)
       at org.openhab.habdroid.core.HabDroidApplication.onCreate(HabDroidApplication.java:11)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
       at android.app.ActivityThread.access$1500(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5350)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalStateException: Expected Android API level 21+ but was 19
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
       at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)
       at org.openhab.habdroid.core.connection.ConnectionFactory.<init>(ConnectionFactory.java:121)
       at org.openhab.habdroid.core.connection.ConnectionFactory.initialize(ConnectionFactory.java:136)
       at org.openhab.habdroid.core.HabDroidApplication.onCreate(HabDroidApplication.java:11)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
       at android.app.ActivityThread.access$1500(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5350)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
````
from 2.6.3-beta on Android 4.
I guess this is caused by https://github.com/openhab/openhab-android/blame/master/mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.java#L119.

**Comment by maniac103** [comment]
I'd rather suspect an OkHttp update:
https://github.com/square/okhttp/commit/bdc7681b3ba16ae311d2dd21160d61315e8942ca
