### ISSUE TITLE
AccessibilityNodeInfo StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1635]
````
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at android.view.accessibility.AccessibilityNodeInfo$CollectionItemInfo.obtain(AccessibilityNodeInfo.java:4770)
       at androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.obtain(AccessibilityNodeInfoCompat.java:793)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfoForItem(RecyclerView.java:10450)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfoForItem(RecyclerView.java:10425)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:143)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:146)
       at androidx.preference.PreferenceRecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(PreferenceRecyclerViewAccessibilityDelegate.java:64)
       at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:8495)
       at android.view.View.createAccessibilityNodeInfoInternal(View.java:8455)
       at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:29157)
       at android.view.View.createAccessibilityNodeInfo(View.java:8438)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1223)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1246)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1048)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:368)
       at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:70)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1412)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
````

2.10.0

Should be fixed by updating https://developer.android.com/jetpack/androidx/releases/recyclerview

**Comment by mueller-ma** [comment]
Still appears in 2.10.2-beta.
