### ISSUE TITLE
PreferencesActivity: SecurityException

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1636]
````
Caused by java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=10694, uid=10140 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:426)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at android.content.ContentResolver.query(ContentResolver.java:422)
       at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:727)
       at android.media.Ringtone.getTitle(Ringtone.java:169)
       at android.media.Ringtone.getTitle(Ringtone.java:150)
       at org.openhab.habdroid.ui.PreferencesActivity$MainSettingsFragment.updateRingtonePreferenceSummary(PreferencesActivity.kt:475)
       at org.openhab.habdroid.ui.PreferencesActivity$MainSettingsFragment.onCreatePreferences(PreferencesActivity.kt:254)
       at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
       at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
       at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
       at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at org.openhab.habdroid.ui.AbstractBaseActivity.onStart(AbstractBaseActivity.kt:78)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
       at android.app.Activity.performStart(Activity.java:6049)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
````

Version 2.10.0

**Comment by maniac103** [comment]
Looks like this can happen if the user selected a ringtone on external storage, since we didn't ask for external storage permission. See https://github.com/consp1racy/android-support-preference/issues/38 for discussion around this.
We probably need to wrap `getTitle()` in a try-catch, and if a SecurityException happens fall back to a sane default summary (the URI? a text like `Unknown ringtone on external storage`?) ... I don't think it's worth implementing external storage runtime permission for this.
