### ISSUE TITLE
ContentController, IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1650]
### Steps to reproduce
1. Configure local url with https to a server with an untrusted cert
2. Configure valid remote connection
3. Leave settings
4. Click on "Cancel" in the MTM dialog

#### Client
* Android version: Android 5
* App version : latest
* Build flavor : Full
* Device language: DE

**Comment by mueller-ma** [comment]
````
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
       at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
       at org.openhab.habdroid.ui.activity.ContentControllerOnePane.executeStateUpdate$mobile_fullBetaRelease(ContentControllerOnePane.kt:50)
       at org.openhab.habdroid.ui.activity.ContentController.updateFragmentState(ContentController.kt:456)
       at org.openhab.habdroid.ui.activity.ContentController.onLoadFailure(ContentController.kt:444)
       at org.openhab.habdroid.ui.activity.PageConnectionHolderFragment$ConnectionHandler$load$1.invokeSuspend(PageConnectionHolderFragment.kt:287)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
````
