### ISSUE TITLE
IllegalStateException: Restarter must be created only during owner's initialization stage

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1801]
````
Fatal Exception: java.lang.IllegalStateException: Restarter must be created only during owner's initialization stage
       at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:58)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2585)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
````

#### Client
* Android version: Multiple
* Device model: Multiple
* App version :  2.11.11-beta
* Build flavor : Full

**Comment by JenniferJohnson89** [comment]
It seems that there is a similar problem at https://github.com/software-mansion/react-native-screens. Perhaps we can refer to https://github.com/software-mansion/react-native-screens/issues/314 to find more context about the bug (e.g. the trigger of the bug, or the steps to reproduce)?

**Comment by EdenYoung1** [comment]
In addition to what @JenniferJohnson89 said, there are also similar issues [material-components-android#389](https://github.com/material-components/material-components-android/issues/389) and  [tindroid#39](https://github.com/tinode/tindroid/issues/39). 
 Maybe  [material-components-android#389(comment)](https://github.com/material-components/material-components-android/issues/389#issuecomment-499756673) and the repair mentioned in https://github.com/tinode/tindroid/issues/39#issuecomment-504371387 can help locate the faulty lines or find how to fix it?

**Comment by mueller-ma** [comment]
I don't see this crash anymore in 2.14.0.
