### ISSUE TITLE
Video widget crash

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1802]
````
Fatal Exception: java.util.concurrent.CancellationException: Task was cancelled.
       at androidx.media2.player.futures.AbstractResolvableFuture.cancellationExceptionWithCause(AbstractResolvableFuture.java:1193)
       at androidx.media2.player.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:515)
       at androidx.media2.player.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:476)
       at androidx.media2.widget.VideoView$3.run(VideoView.java:625)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
````

~~This might be related to Video widgets and untrusted ssl certs.~~ The media player doesn't crash on untrusted certs.

#### Client
* Android version: Multiple
* Device model: Multiple
* App version :  2.11.11-beta
* Build flavor : Full

**Comment by tpham3783** [comment]
Not sure if this is related.  But if I were to have a video widget in basic UI, and that the defined URL points to a non-existing resource, the app crashes every signal time. This is an unpleasant experience, please look into this!

**Comment by mueller-ma** [comment]
Thanks for the hint. Can you tell us your device model and Android version?

**Comment by mueller-ma** [comment]
I added a video widget with an url pointing to no valid video. I just got the following message in the log:
````
03-01 22:27:45.720 7185-7587/org.openhab.habdroid.beta E/ExoPlayerImplInternal: Source error.
    androidx.media2.exoplayer.external.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at androidx.media2.exoplayer.external.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:293)
        at androidx.media2.exoplayer.external.upstream.DefaultDataSource.open(DefaultDataSource.java:178)
        at androidx.media2.exoplayer.external.upstream.StatsDataSource.open(StatsDataSource.java:89)
        at androidx.media2.exoplayer.external.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:942)
        at androidx.media2.exoplayer.external.upstream.Loader$LoadTask.run(Loader.java:387)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
````

**Comment by tpham3783** [comment]
The device is Oneplus 5t, with android 9, oxygenOS version 9.0.10

**Comment by mueller-ma** [comment]
I cannot find the crash in Crashlytics. Can you post the log the next time the app crashes?

**Comment by Sprocket02** [comment]
Maybe I have the same Issue on Oneplus 5T. Sometimes the app crashes when I want to open a mp4 video:

```
--------- beginning of crash
05-13 10:43:59.789 27492 27492 E AndroidRuntime: FATAL EXCEPTION: main
05-13 10:43:59.789 27492 27492 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 27492
05-13 10:43:59.789 27492 27492 E AndroidRuntime: java.util.concurrent.CancellationException: Task was cancelled.
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.cancellationExceptionWithCause(AbstractResolvableFuture.java:1193)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:515)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:476)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at androidx.media2.widget.VideoView$3.run(VideoView.java:666)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6898)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
05-13 10:43:59.789 27492 27492 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Sprocket02** [comment]
I sent some crash logs directly via the app.

**Comment by mueller-ma** [comment]
@maniac103 Any idea how to catch this exception? It isn't thrown by our code.

**Comment by Sprocket02** [comment]
I think the crash of the app has something to do with the cache. The video is updated regularly in the background (motion detection camera). When I open the app after the update, it crashes 2 times. Then it runs again.

**Comment by Sprocket02** [comment]
I still have the problem that the app crashes when I try to open an mp4 file. Here an new log from the app itself. When the app is started for the third time, it usually shows the videos.

```
06-18 08:32:39.196  2781  2781 W MediaPlayer: Couldn't open content://media/internal/audio/media/26
06-18 08:32:39.196  2781  2781 W MediaPlayer: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/internal/audio/media/26
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1438)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1127)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1099)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1011)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.Ringtone.setUri(Ringtone.java:382)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.RingtoneManager.getRingtone(RingtoneManager.java:790)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.RingtoneManager.getRingtone(RingtoneManager.java:765)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.media.RingtoneManager.getRingtone(RingtoneManager.java:728)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at org.openhab.habdroid.ui.PreferencesActivity$MainSettingsFragment.updateRingtonePreferenceSummary(PreferencesActivity.kt:489)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at org.openhab.habdroid.ui.PreferencesActivity$MainSettingsFragment.onCreatePreferences(PreferencesActivity.kt:282)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2001)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at org.openhab.habdroid.ui.AbstractBaseActivity.onStart(AbstractBaseActivity.kt:110)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1521)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.Activity.performStart(Activity.java:7838)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3399)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.os.Looper.loop(Looper.java:214)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
06-18 08:32:39.196  2781  2781 W MediaPlayer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-18 08:32:39.205  2781  2781 E MediaPlayerNative: Unable to create media player
06-18 08:32:39.205  2781  2781 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
06-18 08:32:39.205  2781  2781 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
06-18 08:32:39.205  2781  2781 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
06-18 08:32:39.205  2781  2781 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

And the code snipped from the sitemap file:

```
Text label="Kameras" icon="camera" {
            Frame {
                Text item=Haustuer_motionTime label="Bewegung Haustür:  [%1$ta %1$tR]" icon="motion"
                Video url="http://10.0.0.87:8080/static/cameras/frontdoor_motion.mp4"
            }
            Frame {
                Text item=Klingel_Time label="Klingel Haustür:  [%1$ta %1$tR]" icon="klingel"
                Video url="http://10.0.0.87:8080/static/cameras/frontdoor_ring.mp4"               
            }
        } 
```

Maybe this will help you find the bug?

**Comment by maniac103** [comment]
> `06-18 08:32:39.205  2781  2781 E MediaPlayerNative: Unable to create media player`

Looks like something low-level in your device software is broken. We obviously shouldn't crash on that case, but it's hard to test when one doesn't see such a failure on the own test device...

**Comment by Sprocket02** [comment]
Can I still provide any information to further understand the error? I already sent some crash reports from Google. These should be found in the Dev Center.

**Comment by mueller-ma** [comment]
I reported this to Google in May, but got no response so far: https://issuetracker.google.com/issues/157498395

**Comment by cwihne** [comment]
My bug report #2125 was merged with this one. Video url crashes app. Here my today's log from 2.13.20:
```
08-04 17:29:00.807 12973 12973 E AndroidRuntime: FATAL EXCEPTION: main
08-04 17:29:00.807 12973 12973 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 12973
08-04 17:29:00.807 12973 12973 E AndroidRuntime: java.util.concurrent.CancellationException: Task was cancelled.
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at androidx.concurrent.futures.AbstractResolvableFuture.cancellationExceptionWithCause(AbstractResolvableFuture.java:1192)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at androidx.concurrent.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:514)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at androidx.concurrent.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:475)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at androidx.media2.widget.VideoView$3.run(VideoView.java:673)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8016)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-04 17:29:00.807 12973 12973 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
08-04 17:29:13.854 22513 22513 E b.habdroid.bet: Not starting debugger since process cannot load the jdwp agent.
```
