### ISSUE TITLE
IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1805]
````
Fatal Exception: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1660)
       at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
       at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
       at org.openhab.habdroid.ui.activity.ContentControllerTwoPane.executeStateUpdate$mobile_fullBetaRelease(ContentControllerTwoPane.kt:116)
       at org.openhab.habdroid.ui.activity.ContentController.updateFragmentState(ContentController.kt:456)
       at org.openhab.habdroid.ui.activity.ContentController.onPageUpdated(ContentController.kt:423)
       at org.openhab.habdroid.ui.activity.PageConnectionHolderFragment$ConnectionHandler.triggerUpdate(PageConnectionHolderFragment.kt:245)
       at org.openhab.habdroid.ui.activity.PageConnectionHolderFragment.triggerUpdate(PageConnectionHolderFragment.kt:193)
       at org.openhab.habdroid.ui.activity.ContentController.triggerPageUpdate(ContentController.kt:374)
       at org.openhab.habdroid.ui.MainActivity.triggerPageUpdate(MainActivity.kt:566)
       at org.openhab.habdroid.ui.WidgetListFragment.onStart(WidgetListFragment.kt:143)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at org.openhab.habdroid.ui.AbstractBaseActivity.onStart(AbstractBaseActivity.kt:77)
       at org.openhab.habdroid.ui.MainActivity.onStart(MainActivity.kt:240)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7167)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
````

#### Client
* Android version: Multiple
* Device model: Multiple
* App version :  2.11.11-beta
* Build flavor : Full

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/tbruyelle/RxPermissions. Perhaps we can refer to https://github.com/tbruyelle/RxPermissions/issues/214 to find more context about the bug (e.g. the cause of the bug, or their steps to reproduce). 
Or maybe this can help us find the faulty lines and we can also refer to the https://github.com/tbruyelle/RxPermissions/pull/236 for the bug?

**Comment by mueller-ma** [comment]
There's no report of this crash in 2.12.0 and 2.13.0 anymore, so I'm going to close this.
