### ISSUE TITLE
WebViewFragment: NotFoundException String resource ID #0x2040003

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1808]
````
Fatal Exception: android.view.InflateException: Binary XML file line #9: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at org.openhab.habdroid.ui.activity.WebViewFragment.onCreateView(WebViewFragment.kt:63)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5311)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at org.openhab.habdroid.ui.activity.WebViewFragment.onCreateView(WebViewFragment.kt:63)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5311)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
Caused by android.content.res.Resources$NotFoundException: String resource ID #0x2040003
       at android.content.res.Resources.getText(Resources.java:299)
       at android.content.res.Resources.getString(Resources.java:385)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
       at android.webkit.WebView.<init>(WebView.java:554)
       at android.webkit.WebView.<init>(WebView.java:489)
       at android.webkit.WebView.<init>(WebView.java:472)
       at android.webkit.WebView.<init>(WebView.java:459)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at org.openhab.habdroid.ui.activity.WebViewFragment.onCreateView(WebViewFragment.kt:63)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5311)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
````

Not sure how to fix that. Try/catch WebViewFragment#onCreateView line 63 and show an error toast and finish if there's an error?

#### Client
* Android version: Multiple
* Device model: Multiple
* App version :  2.11.11-beta
* Build flavor : Full

**Comment by mueller-ma** [comment]
Should be fixed when updating appcompat: https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview/57968071#57968071

**Comment by Vall0n** [comment]
Here the link to the issue of the google issue tracker: https://issuetracker.google.com/issues/141132133
