### ISSUE TITLE
DefaultConnection: IllegalArgumentException hostname can't be null

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1825]
````
Fatal Exception: java.lang.IllegalArgumentException: hostname can't be null
       at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:150)
       at java.net.InetSocketAddress.<init>(InetSocketAddress.java:231)
       at org.openhab.habdroid.core.connection.DefaultConnection.isReachableViaNetwork(DefaultConnection.kt:49)
       at org.openhab.habdroid.core.connection.ConnectionFactory.checkAvailableConnection(ConnectionFactory.kt:331)
       at org.openhab.habdroid.core.connection.ConnectionFactory$triggerConnectionUpdateIfNeeded$1$result$1.invokeSuspend(ConnectionFactory.kt:267)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
````

2.11.17-beta

**Comment by maniac103** [comment]
Is this a Firebase report or did you see this yourself?

**Comment by mueller-ma** [comment]
I saw this on Firebase.

**Comment by mueller-ma** [comment]
I can reproduce and submit a PR soon.
