### ISSUE TITLE
App crashes due to network issue

### ISSUE THREAD

**Issue by chihuazhang** [openhab/openhab-android#1956]
Studies have shown that mobile apps are prone to crashes due to a network issue, mainly because successful network calls return unexpected or no data. And we found that when some fields of the app(version 95)'s network return data (json format) are missing or null, the app has crashed. the specific crash information is as follows:

> java.lang.NullPointerException: Null name
	at org.openhab.habdroid.model.$AutoValue_Sitemap$Builder.name($AutoValue_Sitemap.java:142)
	at org.openhab.habdroid.model.Sitemap.fromJson(Sitemap.java:91)
	at org.openhab.habdroid.util.Util.parseSitemapList(Util.java:98)
	at org.openhab.habdroid.model.ServerProperties.loadSitemapsFromJson(ServerProperties.java:173)
	at org.openhab.habdroid.model.ServerProperties.access$300(ServerProperties.java:30)
	at org.openhab.habdroid.model.ServerProperties$2.onSuccess(ServerProperties.java:149)
	at org.openhab.habdroid.model.ServerProperties$2.onSuccess(ServerProperties.java:139)
	at org.openhab.habdroid.util.AsyncHttpClient$1.lambda$onResponse$1(AsyncHttpClient.java:175)
	at org.openhab.habdroid.util.-$$Lambda$AsyncHttpClient$1$dG33YKgGh9PNVJoyi_Y3vffAFHk.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mueller-ma** [comment]
The current version code is `279`, which is usually incremented by 1 for each new beta version. `95` is very old and auto value has been removed since the Kotlin rewrite.
Where did you get this version?
