### ISSUE TITLE
Crash in BackgroundTasksManager

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2019]
````
Fatal Exception: java.lang.NoSuchMethodError: No virtual method isLocationEnabled()Z in class Landroid/location/LocationManager; or its super classes (declaration of 'android.location.LocationManager' appears in /system/framework/framework.jar)
       at org.openhab.habdroid.background.BackgroundTasksManager$Companion$5.invoke(BackgroundTasksManager.kt:476)
       at org.openhab.habdroid.background.BackgroundTasksManager$Companion$5.invoke(BackgroundTasksManager.kt:189)
       at org.openhab.habdroid.background.BackgroundTasksManager$Companion.scheduleWorker(BackgroundTasksManager.kt:370)
       at org.openhab.habdroid.background.BackgroundTasksManager$Companion.access$scheduleWorker(BackgroundTasksManager.kt:189)
       at org.openhab.habdroid.background.BackgroundTasksManager.onReceive(BackgroundTasksManager.kt:93)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3804)
````

2.12.19-beta

**Comment by maniac103** [comment]
That method is available in API 28+ only: https://developer.android.com/reference/android/location/LocationManager#isLocationEnabled()
