### ISSUE TITLE
Notifications related crash in full flavor

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2044]
````
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service org.openhab.habdroid.core.FcmMessageListenerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3745)
       at android.app.ActivityThread.access$1400(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at android.content.ContextWrapper.getSystemService(ContextWrapper.java:741)
       at org.openhab.habdroid.core.NotificationHelper.<init>(NotificationHelper.kt:41)
       at org.openhab.habdroid.core.FcmMessageListenerService.<init>(FcmMessageListenerService.kt:23)
       at java.lang.Class.newInstance(Class.java)
       at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
       at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3740)
       at android.app.ActivityThread.access$1400(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
````

#### Client
* Android version: Multiple
* Device model: Multiple
* App version : 2.13.1-beta 
* Build flavor : Full
* Device language: Multiple

**Comment by scatterthought** [comment]
I'm not sure if this is the same issue, but I noticed with the new release that notifications are no longer working in the beta app. The notifications are sent by myopenhab and show up in the app, but there's nothing in the Android notification bar. I installed and tested the public release and notifications still work in that version.

**Comment by kirkpensalvo** [comment]
@scatterthought I'm seeing the same. I have a test button that will send me a test notification that as soon as I push, the app crashes and closes. Public release works correctly.

**Comment by spikez** [comment]
Same issue on 2.13.4-beta. No Notifications or App Crash.

**Comment by mueller-ma** [comment]
@maniac103 Can you have a look at this issue? I'm clueless how this can happen.

**Comment by maniac103** [comment]
I'll check it.

**Comment by scatterthought** [comment]
I tried to send a test message from myopenhab that didn't appear at all in 2.13.4-beta, whereas with 2.13.1-beta it showed up in the Notifications list (but didn't trigger an Android notification). When I sent a second test message, 2.13.4-beta crashed.

Cheers!

**Comment by maniac103** [comment]
Sent a test message from the myopenhab web UI? If so, those should *never* appear in the notifications list.

**Comment by scatterthought** [comment]
Well that's interesting. I'm fairly certain that when I tested 2.13.1-beta, the notification showed up in the list in the app. But now it doesn't.

**Comment by mueller-ma** [comment]
> Sent a test message from the myopenhab web UI? If so, those should never appear in the notifications list.

The notifications sent via the myopenHAB web UI are just for testing and not saved as the regular notifications.

**Comment by scatterthought** [comment]
Good to know. I'm certain it happened, because I said as much in my first comment on this issue. If I hadn't seen my test message in the notification list, I would have said as much (assuming that it was supposed to show up).

**Comment by maniac103** [comment]
This is what I get on Firebase registration:
```
06-17 07:04:00.067  6011  6137 W Firebase-Installations: Error when communicating with the Firebase Installations server API. HTTP response: [403 Forbidden: {
06-17 07:04:00.067  6011  6137 W Firebase-Installations:   "error": {
06-17 07:04:00.067  6011  6137 W Firebase-Installations:     "code": 403,
06-17 07:04:00.067  6011  6137 W Firebase-Installations:     "message": "Requests from this Android client application org.openhab.habdroid.beta are blocked.",
06-17 07:04:00.067  6011  6137 W Firebase-Installations:     "status": "PERMISSION_DENIED",
06-17 07:04:00.067  6011  6137 W Firebase-Installations:     "details": [
06-17 07:04:00.067  6011  6137 W Firebase-Installations:       {
06-17 07:04:00.067  6011  6137 W Firebase-Installations:         "@type": "type.googleapis.com/google.rpc.Help",
06-17 07:04:00.067  6011  6137 W Firebase-Installations:         "links": [
06-17 07:04:00.067  6011  6137 W Firebase-Installations:           {
06-17 07:04:00.067  6011  6137 W Firebase-Installations:             "description": "Google developer console API key",
06-17 07:04:00.067  6011  6137 W Firebase-Installations:             "url": "https://console.developers.google.com/project/849058498762/apiui/credential"
06-17 07:04:00.067  6011  6137 W Firebase-Installations:           }
06-17 07:04:00.067  6011  6137 W Firebase-Installations:         ]
06-17 07:04:00.067  6011  6137 W Firebase-Installations:       }
06-17 07:04:00.067  6011  6137 W Firebase-Installations:     ]
06-17 07:04:00.067  6011  6137 W Firebase-Installations:   }
06-17 07:04:00.067  6011  6137 W Firebase-Installations: }
06-17 07:04:00.067  6011  6137 W Firebase-Installations: ]
06-17 07:04:00.067  6011  6137 W Firebase-Installations: Firebase options used while communicating with Firebase server APIs: xxx openhab-mobile, 1:xxx:android:xxx
06-17 07:04:00.067  6011  6137 E Firebase-Installations: Firebase Installations can not communicate with Firebase server APIs due to invalid configuration. Please update your Firebase initialization process and set valid Firebase options (API key, Project ID, Application ID) when initializing Firebase.
```

Because of that I don't even get to the crashing point. @scatterthought Can you repro the 'sending message doesn't do anything' condition? If so, please share the app log after that happening.

**Comment by maniac103** [comment]
Downgrading to Firebase 20.1.0 makes FCM registration work again for me. See here: https://stackoverflow.com/a/61309137 ... looks like something needs to be adapted in the cloud services setup. When doing so, please make sure to keep a way for running a self-built apk with notification support.

**Comment by cwihne** [comment]
I experience same issue, beta app instantly crashing on reception of a OH notification message, regardless of source OH server or test message on myopenhab.org and regardless of local (direct) or remote (Cloud) connection. Happens since "new" version of beta, 2.13.x. Running in parallel to released OH Andoid app, which receives messages without any issues. I re-established connection of both app versions to myopenhab just yesterday, to exclude that part from the issue. Hoping that this log section helps, identified by crash timestamp:
```
--------- beginning of main
06-24 09:00:49.099  8890  8890 D ViewRootImpl@75b56a4[LogActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
06-24 09:00:49.099  8890  8890 D InputMethodManager: prepareNavigationBarInfo() DecorView@dbb30a8[LogActivity]
06-24 09:00:49.099  8890  8890 D InputMethodManager: getNavigationBarColor() -16777216
06-24 09:00:56.308  8890  8890 D ViewRootImpl@75b56a4[LogActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
06-24 09:00:56.308  8890  8890 D InputMethodManager: prepareNavigationBarInfo() DecorView@dbb30a8[LogActivity]
06-24 09:00:56.308  8890  8890 D InputMethodManager: getNavigationBarColor() -16777216
06-24 09:01:06.351  8890  8890 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-24 09:01:06.352  8890  8890 E AndroidRuntime: FATAL EXCEPTION: main
06-24 09:01:06.352  8890  8890 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 8890
06-24 09:01:06.352  8890  8890 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service org.openhab.habdroid.core.FcmMessageListenerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.ActivityThread.handleCreateService(ActivityThread.java:4269)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.ActivityThread.access$1800(ActivityThread.java:272)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:107)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8016)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.content.ContextWrapper.getSystemService(ContextWrapper.java:766)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at org.openhab.habdroid.core.NotificationHelper.<init>(NotificationHelper.kt:41)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at org.openhab.habdroid.core.FcmMessageListenerService.<init>(FcmMessageListenerService.kt:23)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at java.lang.Class.newInstance(Native Method)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: at android.app.ActivityThread.handleCreateService(ActivityThread.java:4264)
06-24 09:01:06.352  8890  8890 E AndroidRuntime: ... 8 more
06-24 09:01:06.423  8890  8935 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
06-24 09:01:06.423  8890  8935 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
06-24 09:01:07.205  8890  8935 I CrashlyticsCore: Crashlytics report upload complete: 5EF2FA070322-0001-22BA-3860A4FE6C64
```
Let me know section of interest from app starting log, like this, 1s after app restart:
```
06-24 09:01:32.221  9572  9572 D MainActivity: onCloudConnectionChanged()
06-24 09:01:32.230  9572  9703 D FcmRegistrationService: Register device at openHAB-cloud with URL: addAndroidRegistration?deviceId=076679dd4889f6ff-beta&deviceModel=Samsung+SM-G973F+%28Beta%29&regId=eoAyzoANRhG2k8J...
06-24 09:01:32.230  9572  9685 I okhttp.OkHttpClient: --> GET https://<openhab-remote-address>/addAndroidRegistration?deviceId=076679dd4889f6ff-beta&deviceModel=Samsung+SM-G973F+%28Beta%29&regId=eoAyzoANRhG2k8J...
```

**Comment by cwihne** [comment]
App 2.13.7-beta brings back notification messages. Thank you @maniac103 and @mueller-ma .

**Comment by CSchlipp** [comment]
But 2.13.10 is unfortunately broken again...

**Comment by cwihne** [comment]
> 
> 
> But 2.13.10 is unfortunately broken again...

Yepp, I sadly agree.

**Comment by maniac103** [comment]
Broken in what way exactly? If a crash, please share the app log. If anything else, please elaborate.

**Comment by cwihne** [comment]
I should have thought that far initially, sorry. 
The above results from sendNotification in rule. Crash can similarly be triggered with any message from myopenhab cloud service, regardless of androidapp running in front or background. It crashes instantly.
Here crash log after sendNotification in rule:
```
--------- beginning of crash
07-09 08:43:26.425  8939  8939 E AndroidRuntime: FATAL EXCEPTION: main
07-09 08:43:26.425  8939  8939 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 8939
07-09 08:43:26.425  8939  8939 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.tasks.Task com.google.firebase.iid.WithinAppServiceBinder$IntentHandler.zza(android.content.Intent)"
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at com.google.firebase.iid.WithinAppServiceBinder.zza(com.google.firebase:firebase-iid@@20.2.2:9)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at com.google.firebase.iid.zzaw.zza(com.google.firebase:firebase-iid@@20.2.2:30)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at com.google.firebase.iid.zzaw.onServiceConnected(com.google.firebase:firebase-iid@@20.2.2:59)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2067)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2099)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8016)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-09 08:43:26.425  8939  8939 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
07-09 08:43:26.448  8939  8991 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-09 08:43:26.448  8939  8991 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-09 08:43:26.456  8939  8939 I Process : Sending signal. PID: 8939 SIG: 9
```
(determined by timecode. Anything after this relates to app restart. Let me know section of interest if you need.)

**Comment by maniac103** [comment]
Thanks. Nicely, done, Google, since the crash is in the FCM lib. I suspect the update in #2085 was broken then, let's hope the update in #2089 has this fixed. The [release notes](https://firebase.google.com/support/release-notes/android#messaging_v20-2-3) can at least be interpreted that way.

**Comment by mueller-ma** [comment]
I just released 2.13.11-beta including the fix.

**Comment by cwihne** [comment]
2.13.11: Notifications are back. Both from sendNotification and myopenhab. Impressed I am. Thank you.

**Comment by CSchlipp** [comment]
Can confirm as well that it's working again in 2.13.11.

Sorry for not adding the application log, it was way too late yesterday. Today morning @cwihne was a bit faster than me ;)

Thanks for the quick fix!
