### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2206]
```
Fatal Exception: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=background pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x42 color=0xffff5722 category=progress vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2137)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

Here's the place throwing the exception:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r46/services/core/java/com/android/server/am/ActiveServices.java#836
called from here:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r46/services/core/java/com/android/server/am/ServiceRecord.java#900

Unfortunately from there it becomes fuzzy, at least as long as we don't have the logcat output. Obvious causes are no channel (line 878) or no small icon (line 888), both of which don't seem the case here. Besides that, it's only NotificationManagerService.enqueueNotificationInternal (via here: https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r46/services/core/java/com/android/server/notification/NotificationManagerService.java#4622) that could throw then, and it's less obvious there. I totally can't see contentText being required to be non-null though.

Is this crash occuring to a single user only?

_Originally posted by @maniac103 in https://github.com/openhab/openhab-android/pull/2198#issuecomment-689454013_

**Comment by mueller-ma** [comment]
I don't see this issue anymore in Crashlytics.
