### ISSUE TITLE
VoiceCommand not updateing/working

### ISSUE THREAD

**Issue by dchristl** [openhab/openhab-android#2503]
### Actual behaviour
The voice command option in the upper right corner is not working anymore. The spoken words seems to be recognized correctly, but the app always quit with "item could not be updated" notification. (Update failed with http code 400)

### Expected behaviour
The voice command should update the "VoiceCommand"-Item. 

 
### Steps to reproduce

1. Open OpenHab-App (Release or Beta-Version)
2. Press recorder in the upper right corner
3. Speak any sentence/word
4. Error with notfication

### Can you reproduce the issue in demo mode?
Yes, exactly the same

#### Client
* Android version:  9 
* Device model: Huawei P10 VKY-L29
* App version : 2.16.13-beta
* Build flavor: Play store
* Device language: German

#### Server
* Server version: Openhab 3.0.1 - Release Build
* Reverse Proxy: No
* Authentication method: None

#### App log
<details>
  <summary>Click to expand</summary>

````
03-29 14:38:24.814 20887 20887 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-29 14:38:35.131 20887 20887 V InputMethodManager: Reporting focus gain, without startInput
03-29 14:38:36.822 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:36.822 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:36.822 20887 20887 D LogActivity: onOptionsItemSelected()
--------- beginning of events
03-29 14:38:36.852 20887 20887 I am_on_paused_called: [0,org.openhab.habdroid.ui.LogActivity,performPause]
03-29 14:38:36.853 20887 20887 D ZrHung.AppEyeUiProbe: stop checker.
03-29 14:38:36.922 20887 20887 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-29 14:38:36.926 20887 20887 I am_on_restart_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performRestartActivity]
03-29 14:38:36.934 20887 20887 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=desktop, label=Zu Hause), wifiSsid=null)
03-29 14:38:36.937 20887 20887 I am_on_start_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handleStartActivity]
03-29 14:38:36.937 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:36.940 20887 20887 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,RESUME_ACTIVITY]
03-29 14:38:36.954 20887 20935 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-29 14:38:36.957 20887 20974 D ConnectionFactory: checkAvailableConnection: found types [ConnectionType(type = Wifi, network=111)]
03-29 14:38:36.957 20887 20974 D AbstractConnection: Checking reachability of http://<openhab-local-address-openHAB>:8080/ (via 111)
03-29 14:38:36.978 20887 20974 D AbstractConnection: Socket connected (attempt 0)
03-29 14:38:36.979 20887 20974 D ConnectionFactory: Connecting to local URL via ConnectionType(type = Wifi, network=111)
03-29 14:38:36.981 20887 20887 W InputMethodManager: startInputReason = 1
03-29 14:38:37.223 20887 20935 W libEGL : EGLNativeWindowType 0x7dc4448010 disconnect failed
03-29 14:38:37.224 20887 20935 D OpenGLRenderer: endAllActiveAnimators on 0x7de1016500 (RippleDrawable) with handle 0x7dfb4f9960
03-29 14:38:37.232 20887 20887 D ViewRootImpl[LogActivity]: surface should not be released
03-29 14:38:37.233 20887 20887 I am_on_stop_called: [0,org.openhab.habdroid.ui.LogActivity,LIFECYCLER_STOP_ACTIVITY]
03-29 14:38:37.233 20887 20887 I am_on_destroy_called: [0,org.openhab.habdroid.ui.LogActivity,performDestroy]
--------- beginning of system
03-29 14:38:37.233 20887 20887 D ActivityThread: Remove activity client record, r= ActivityRecord{182d0a8 token=android.os.BinderProxy@ecdf5ca {org.openhab.habdroid.beta/org.openhab.habdroid.ui.LogActivity}} token= android.os.BinderProxy@ecdf5ca
03-29 14:38:38.136 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:38.136 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:38.157 20887 20887 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
03-29 14:38:38.158 20887 20887 D ZrHung.AppEyeUiProbe: stop checker.
03-29 14:38:38.206 20887 20887 D MainActivity: onActivityResult() requestCode = 1001, resultCode = -1
03-29 14:38:38.207 20887 20887 I am_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT]
03-29 14:38:38.209 20887 20887 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
03-29 14:38:38.211 20887 20887 D MainActivity: onStart()
03-29 14:38:38.211 20887 20887 D PageConnectionHolderFragment: onStart(), started false
03-29 14:38:38.212 20887 20887 D PageConnectionHolderFragment: Loading data for http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop, long polling false
03-29 14:38:38.212 20887 20887 D WidgetListFragment: onStart() http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop
03-29 14:38:38.212 20887 20887 D PageConnectionHolderFragment: Trigger update for URL http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop, force false
03-29 14:38:38.212 20887 20887 D ContentController: Got update for URL http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop, pending []
03-29 14:38:38.217 20887 20887 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=desktop, label=Zu Hause), wifiSsid=null)
03-29 14:38:38.220 20887 20887 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=desktop, label=Zu Hause), wifiSsid=null)
03-29 14:38:38.226 20887 20887 D MainActivity: onActiveConnectionChanged()
03-29 14:38:38.236 20887 20887 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=desktop, label=Zu Hause), wifiSsid=null)
03-29 14:38:38.236 20887 20887 D MainActivity: Cannot auto select server: No server with configured wifi
03-29 14:38:38.236 20887 20887 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
03-29 14:38:38.237 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:38.238 20887 20887 D MainActivity: onResume()
03-29 14:38:38.243 20887 20887 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
03-29 14:38:38.268 20887 20935 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-29 14:38:38.289 20887 20887 W InputMethodManager: startInputReason = 1
03-29 14:38:38.353 20887 20887 D PageConnectionHolderFragment: Updated page data for URL http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop (8 widgets)
03-29 14:38:38.353 20887 20887 D ContentController: Got update for URL http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop, pending []
03-29 14:38:38.516 20887 20935 W libEGL : EGLNativeWindowType 0x7dcfeac010 disconnect failed
03-29 14:38:38.516 20887 20935 D OpenGLRenderer: endAllActiveAnimators on 0x7de0d4ba00 (RippleDrawable) with handle 0x7dcd5fca80
03-29 14:38:38.523 20887 20887 D ViewRootImpl[PreferencesActivity]: surface should not be released
03-29 14:38:38.523 20887 20887 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,LIFECYCLER_STOP_ACTIVITY]
03-29 14:38:38.525 20887 20887 I am_on_destroy_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performDestroy]
03-29 14:38:38.525 20887 20887 D ActivityThread: Remove activity client record, r= ActivityRecord{da1e7ac token=android.os.BinderProxy@f237302 {org.openhab.habdroid.beta/org.openhab.habdroid.ui.PreferencesActivity}} token= android.os.BinderProxy@f237302
03-29 14:38:39.031 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:39.031 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:39.031 20887 20887 I menu_item_selected: [0,Sprachbefehl]
03-29 14:38:39.031 20887 20887 D MainActivity: onOptionsItemSelected()
03-29 14:38:39.074 20887 20887 D MainActivity: onPause()
03-29 14:38:39.074 20887 20887 D WidgetListFragment: onPause() http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop
03-29 14:38:39.075 20887 20887 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
03-29 14:38:39.075 20887 20887 D ZrHung.AppEyeUiProbe: stop checker.
03-29 14:38:39.466 20887 20928 D ZrHung.AppEyeUiProbe: Current Activity:false
03-29 14:38:39.466 20887 20928 D ZrHung.AppEyeUiProbe: not watching, wait.
03-29 14:38:41.586 20887 20887 D BackgroundTasksManager: onReceive() with intent org.openhab.habdroid.background.action.VOICE_RESULT
03-29 14:38:41.587 20887 20887 I BackgroundTasksManager: Recognized text: Essen
03-29 14:38:41.588 20887 20887 D BackgroundTasksManager: Scheduling work for tag voiceCommand
03-29 14:38:41.681 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:41.682 20887 20928 D ZrHung.AppEyeUiProbe: restart watching
03-29 14:38:41.682 20887 20887 D MainActivity: onResume()
03-29 14:38:41.704 20887 20887 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
03-29 14:38:41.705 20887 20887 W InputMethodManager: startInputReason = 1
03-29 14:38:41.709 20887 20927 D HwCustConnectivityManagerImpl: isBlockNetworkRequestByNonAis, INVALID_SUBSCRIPTION_ID
03-29 14:38:41.709 20887 20927 D ConnectivityManager: requestNetwork and the calling app is: org.openhab.habdroid.beta
03-29 14:38:41.716 20887 20887 D BackgroundTasksManager: onReceive() with intent org.openhab.habdroid.background.action.VOICE_RESULT
03-29 14:38:41.716 20887 20887 I BackgroundTasksManager: Recognized text: Essen
03-29 14:38:41.717 20887 20887 D BackgroundTasksManager: Scheduling work for tag voiceCommand
03-29 14:38:41.724 20887 21334 D ItemUpdateWorker: Trying to get connection
03-29 14:38:41.741 20887 20927 D HwCustConnectivityManagerImpl: isBlockNetworkRequestByNonAis, INVALID_SUBSCRIPTION_ID
03-29 14:38:41.741 20887 20927 D ConnectivityManager: requestNetwork and the calling app is: org.openhab.habdroid.beta
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: Work [ id=169fd077-b21e-4dfe-86a1-d35d32c9f5ab, tags={ itemUploads, server-id-1, org.openhab.habdroid.background.ItemUpdateWorker, voiceCommand } ] was cancelled
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-29 14:38:41.743 20887 20927 I WM-WorkerWrapper: at java.lang.Thread.run(Thread.java:784)
03-29 14:38:41.746 20887 20887 I WM-SystemFgDispatcher: Stopping foreground service
03-29 14:38:41.755 20887 21010 D ItemUpdateWorker: Trying to get connection
03-29 14:38:41.756 20887 20930 I WM-Processor: Moving WorkSpec (9a9e2d27-fdfa-4043-be55-2d506627084a) to the foreground
03-29 14:38:41.765 20887 20887 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=org.openhab.habdroid.beta/androidx.work.impl.foreground.SystemForegroundService (has extras) }
03-29 14:38:41.771 20887 20916 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=9a9e2d27-fdfa-4043-be55-2d506627084a, tags={ itemUploads, server-id-1, org.openhab.habdroid.background.ItemUpdateWorker, voiceCommand } ]
03-29 14:38:41.774 20887 20887 I WM-SystemFgDispatcher: Stopping foreground service
03-29 14:38:41.786 20887 20887 E b.habdroid.bet: Invalid ID 0x00000000.
03-29 14:38:43.439 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:43.439 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:43.441 20887 20887 D MainActivity: onOptionsItemSelected()
03-29 14:38:43.634 20887 20887 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-29 14:38:44.150 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:44.150 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:44.171 20887 20887 D MainActivity: onPause()
03-29 14:38:44.171 20887 20887 D WidgetListFragment: onPause() http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop
03-29 14:38:44.172 20887 20887 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
03-29 14:38:44.173 20887 20887 D ZrHung.AppEyeUiProbe: stop checker.
03-29 14:38:44.184 20887 20887 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f5e96ad
03-29 14:38:44.184 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:44.184 20887 20887 V ActivityThread: Skipping new config:{1.0 262mcc2mnc [de_DE] ldltr sw411dp w411dp h704dp 420dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.129}, config:{1.0 262mcc2mnc [de_DE] ldltr sw411dp w411dp h704dp 420dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.129} for app:org.openhab.habdroid.beta
03-29 14:38:44.187 20887 20887 V ActivityThread: callActivityOnCreate
03-29 14:38:44.191 20887 20887 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
03-29 14:38:44.191 20887 20887 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
03-29 14:38:44.195 20887 20887 I am_on_create_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performCreate]
03-29 14:38:44.196 20887 20887 D ActivityThread: add activity client record, r= ActivityRecord{1d070bf token=android.os.BinderProxy@f5e96ad {org.openhab.habdroid.beta/org.openhab.habdroid.ui.PreferencesActivity}} token= android.os.BinderProxy@f5e96ad
03-29 14:38:44.200 20887 20887 V AudioManager: getRingtonePlayer...
03-29 14:38:44.200 20887 20887 I Ringtone: setUri uri=content://settings/system/notification_sound
03-29 14:38:44.214 20887 20887 W MediaStore: IllegalArgumentException when getDataColumn
03-29 14:38:44.215 20887 20887 I MediaPlayerNative: setDataSource(98, 0, 576460752303423487)
03-29 14:38:44.217 20887 20887 D MediaPlayerNative: MediaPlayer::setVolume(1.000000, 1.000000)
03-29 14:38:44.217 20887 20887 D MediaPlayerNative: MediaPlayer::setVolume(1.000000, 1.000000)
03-29 14:38:44.217 20887 20887 I PlayerBase: isRestricted: falseLeftvolume: 1.0 Rightvolume: 1.0mPanMultiplierL: 1.0mPanMultiplierR: 1.0
03-29 14:38:44.226 20887 20887 D Ringtone: Successfully created local player
03-29 14:38:44.230 20887 20887 D PreferencesActivity: Removing notification prefs for < 25
03-29 14:38:44.231 20887 20887 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.231 20887 20887 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.231 20887 20887 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.231 20887 20887 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
03-29 14:38:44.231 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@3e21290,org.openhab.habdroid.ui.PreferencesActivity@67af0a9
03-29 14:38:44.231 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
03-29 14:38:44.232 20887 20887 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.232 20887 20887 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.232 20887 20887 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:44.232 20887 20887 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
03-29 14:38:44.232 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@efdc7bc,org.openhab.habdroid.ui.PreferencesActivity@67af0a9
03-29 14:38:44.232 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
03-29 14:38:44.234 20887 20887 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=desktop, label=Zu Hause), wifiSsid=null)
03-29 14:38:44.234 20887 20887 I am_on_start_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handleStartActivity]
03-29 14:38:44.234 20887 20887 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=true, navigationBarColor=ff121212, mNavBarShow=false, mIsFloating=false
03-29 14:38:44.234 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:44.235 20887 20887 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,RESUME_ACTIVITY]
03-29 14:38:44.236 20887 20935 D OpenGLRenderer: HWUI Binary is enabled
03-29 14:38:44.243 20887 24697 I HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
03-29 14:38:44.243 20887 24697 D HiTouch_PressGestureDetector: onAttached, package=org.openhab.habdroid.beta, windowType=1, mHiTouchRestricted=false
03-29 14:38:44.251 20887 20935 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-29 14:38:44.298 20887 20935 D OpenGLRenderer: HWUI Binary is enabled
03-29 14:38:44.300 20887 20887 W InputMethodManager: startInputReason = 1
03-29 14:38:44.548 20887 20935 W libEGL : EGLNativeWindowType 0x7dc4448010 disconnect failed
03-29 14:38:44.557 20887 20887 D ViewRootImpl[MainActivity]: surface should not be released
03-29 14:38:44.557 20887 20887 D MainActivity: onStop()
03-29 14:38:44.557 20887 20887 D PageConnectionHolderFragment: onStop()
03-29 14:38:44.557 20887 20887 D PageConnectionHolderFragment: Canceling connection for URL http://<openhab-local-address-openHAB>:8080/rest/sitemaps/desktop/desktop
03-29 14:38:44.558 20887 20887 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,STOP_ACTIVITY_ITEM]
03-29 14:38:44.558 20887 20887 D MainActivity: onSaveInstanceState()
03-29 14:38:44.558 20887 20887 D ContentController: onSaveInstanceState()
03-29 14:38:45.583 20887 20887 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
03-29 14:38:45.583 20887 20887 V HiTouch_HiTouchSensor: User setup is finished.
03-29 14:38:45.602 20887 20887 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:2.8760986, limit is:53The moving distance of Y is:66.83057, limit is:53
03-29 14:38:45.697 20887 20887 D OverScrollerOptimization: fling time is flingTime = 2.806812590309641 velocity = 6336
03-29 14:38:45.697 20887 20887 I chatty : uid=10099(org.openhab.habdroid.beta) identical 2 lines
03-29 14:38:45.697 20887 20887 D OverScrollerOptimization: fling time is flingTime = 2.806812590309641 velocity = 6336
03-29 14:38:45.760 20887 20887 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
03-29 14:38:47.147 20887 20887 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:0.3534546, limit is:53The moving distance of Y is:129.24805, limit is:53
03-29 14:38:47.212 20887 20887 D OverScrollerOptimization: fling time is flingTime = 2.8374087084891526 velocity = 6714
03-29 14:38:47.212 20887 20887 I chatty : uid=10099(org.openhab.habdroid.beta) identical 2 lines
03-29 14:38:47.212 20887 20887 D OverScrollerOptimization: fling time is flingTime = 2.8374087084891526 velocity = 6714
03-29 14:38:48.709 20887 20887 V AudioManager: playSoundEffect effectType: 0
03-29 14:38:48.709 20887 20887 V AudioManager: querySoundEffectsEnabled...
03-29 14:38:48.741 20887 20887 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-29 14:38:48.742 20887 20887 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
03-29 14:38:48.742 20887 20887 D ZrHung.AppEyeUiProbe: stop checker.
03-29 14:38:48.753 20887 20887 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@76ceeb5
03-29 14:38:48.753 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:48.753 20887 20887 V ActivityThread: Skipping new config:{1.0 262mcc2mnc [de_DE] ldltr sw411dp w411dp h704dp 420dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.129}, config:{1.0 262mcc2mnc [de_DE] ldltr sw411dp w411dp h704dp 420dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.129} for app:org.openhab.habdroid.beta
03-29 14:38:48.755 20887 20887 V ActivityThread: callActivityOnCreate
03-29 14:38:48.760 20887 20887 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
03-29 14:38:48.760 20887 20887 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
03-29 14:38:48.764 20887 20887 I FloatingActionButton: Setting a custom background is not supported.
03-29 14:38:48.767 20887 20887 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
03-29 14:38:48.767 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@e35b7d3,org.openhab.habdroid.ui.LogActivity@d4ac131
03-29 14:38:48.767 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
03-29 14:38:48.767 20887 20887 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
03-29 14:38:48.767 20887 20887 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
03-29 14:38:48.767 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@719fe2f,org.openhab.habdroid.ui.LogActivity@d4ac131
03-29 14:38:48.767 20887 20887 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
03-29 14:38:48.771 20887 20887 I am_on_create_called: [0,org.openhab.habdroid.ui.LogActivity,performCreate]
03-29 14:38:48.771 20887 20887 D ActivityThread: add activity client record, r= ActivityRecord{b524e4b token=android.os.BinderProxy@76ceeb5 {org.openhab.habdroid.beta/org.openhab.habdroid.ui.LogActivity}} token= android.os.BinderProxy@76ceeb5
03-29 14:38:48.772 20887 20887 I am_on_start_called: [0,org.openhab.habdroid.ui.LogActivity,handleStartActivity]
03-29 14:38:48.772 20887 20887 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=true, navigationBarColor=ff121212, mNavBarShow=false, mIsFloating=false
03-29 14:38:48.773 20887 20887 D ZrHung.AppEyeUiProbe: notify runnable to start.
03-29 14:38:48.773 20887 20887 I am_on_resume_called: [0,org.openhab.habdroid.ui.LogActivity,RESUME_ACTIVITY]
03-29 14:38:48.774 20887 20935 D OpenGLRenderer: HWUI Binary is enabled
03-29 14:38:48.783 20887 24706 I HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
03-29 14:38:48.784 20887 24706 D HiTouch_PressGestureDetector: onAttached, package=org.openhab.habdroid.beta, windowType=1, mHiTouchRestricted=false
03-29 14:38:48.801 20887 20935 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-29 14:38:48.801 20887 20935 D OpenGLRenderer: HWUI Binary is enabled
03-29 14:38:48.816 20887 20887 D LogActivity: onCreateOptionsMenu()

````

</details>

#### openHAB Server log
No entry

**Comment by Trysupe** [comment]
I just tested this on my system and I do not have this issue. The item gets updated properly.

Running openHAB 2.5-12 and Android App 2.16-13 beta

**Comment by dchristl** [comment]
Is there any way to figure this out? Everything else is working fine  What command is called when this is enabled? 
If I call 
`curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "essen" "http://<IP>:8080/rest/items/VoiceCommand"`
directly the right command gets called.

**Comment by Trysupe** [comment]
>Is there any way to figure this out?

I think the app communicates with the server over the REST API. So if the `curl` command works this is the first step. For any further advice we might have to ask @mueller-ma how the call from the app works. I tried to figure it out, however I do not have any kotlin knowledge^^

**Comment by mueller-ma** [comment]
The app calls the REST Api `rest/voice/interpreters`. This api redirects your command to either the built-in interpreter or to the rule based one. The behavior is described in https://www.openhab.org/docs/apps/android.html#my-voice-command-rule-isn-t-run
However the docs haven't been adopted for openHAB 3, so I have to check that and edit the docs.

**Comment by dchristl** [comment]
OK, It seems I figured it out. I checked out the code and the app seems to call "rest/voice/interpreters" in the first place. After trying that with curl I get the response:
`{"error":{"message":"Entschuldigung. Ich habe das nicht verstanden.","http-code":400}`
I switched the intrepreter in openHab to "Built in" -> Save and back to "Rule-based interpreter"  and now the result with curl was empty. I don't know what the correct output is, but after that the app seems to work again. So, this is no error in the app, it is an openhab one. Maybe there was a problem or a bug with the 3.0.1 release. Thanks for your time, but this bug can be closed.

**Comment by mueller-ma** [comment]
Can you post your curl command? I'll try that on my openHAB server as well.

**Comment by dchristl** [comment]
> Can you post your curl command? I'll try that on my openHAB server as well.
Yes, of course, it seems we are commenting at the same time. The command was:

`curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "essen" "http://<IP>:8080/rest/voice/interpreters"`

**Comment by mueller-ma** [comment]
> Maybe there was a problem or a bug with the 3.0.1 release. 

I wasn't able to reproduce this with the curl command above.
