### ISSUE TITLE
[Samsung] Can't share app Log

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2546]
I recently upgraded from my OnePlus 7T Pro to my new Samsung Galaxy S21 Ultra

### Actual behaviour
While opening another issue I noticed that the share button in the App for the log does not work. See this [screen recording](https://drive.google.com/file/d/1OwkoediHDY6CEhIwc5a3gK0uHuyWGsXK/view?usp=sharing)
I was not able to upload the recording since it is to big for github...

Instead of opening the menu to show the apps to share the log with it just reloads the log.

### Expected behaviour
Share the log in other apps like it works on the OnePlus phone

 
#### Client
* Android version: 11
* Device model: Samsung Galaxy S21 Ultra
* App version : 2.16.18
* Build flavor : Full
* Device language: German

#### App log
[log.txt](https://github.com/openhab/openhab-android/files/6386049/log.txt)

**Comment by Trysupe** [comment]
Does happen in the non beta version (2.16.0) as well

**Comment by Trysupe** [comment]
As one can see I noticed three things not working in the app not working on my samsung device which worked flawlessly as expected on my OnePlus device:
- https://github.com/openhab/openhab-android/issues/2546
- https://github.com/openhab/openhab-android/issues/2547
- https://github.com/openhab/openhab-android/issues/2548

**Comment by mueller-ma** [comment]
Can you clear the log and then try to share it?

**Comment by Trysupe** [comment]
> Can you clear the log and then try to share it?

Yes this [works](https://drive.google.com/file/d/18NkKBJh8V_avLumzr1fS5SeMI4eMpsPP/view?usp=sharing)

**Comment by mueller-ma** [comment]
If the log is too large it cannot be shared to other apps the way we do it here. In the case all devices I tried throw an exception, which is catched by the app and a hint is shown: "The log is too large to share. Please clear the log, reproduce the bug and share the log then."
It seems that Samsung devices don't throw an exception and just silently drop the share request.

Can you try to capture the log directly with ADB when clicking on the share button and it fails to share? There might be a line like `JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4896252)`. The lines before and after this is important.

**Comment by Trysupe** [comment]
> If the log is too large it cannot be shared to other apps the way we do it here. In the case all devices I tried throw an exception, which is catched by the app and a hint is shown: "The log is too large to share. Please clear the log, reproduce the bug and share the log then."

Hmmmm, so the log has to be really small to be shared since even launching the app (after completely stopping it), opening a frame and then trying to share the log already fails.

Is the log resetted every time the app is (forcefully) closed and reopened?

-----



> Can you try to capture the log directly with ADB

I can try I guess. I only did some super simple adb stuff a long time ago. Is there a good manual on how to this online? I found [this article](https://developer.android.com/studio/command-line/logcat) from google and [this one](https://support.citrix.com/article/CTX232375).

**Comment by Trysupe** [comment]
```
04-29 12:18:28.994  1389  4483 E ActivityTaskManager: Transaction too large, intent: Intent { act=android.intent.action.SEND typ=text/plain flg=0x800001 cmp=android/com.android.internal.app.ResolverActivity clip={text/plain {...}} (has extras) }, extras size: 640252, icicle size: 0
04-29 12:18:28.994  1389  4483 D PkgDataHelper: notifyAppCreate(), pkgName: android, sendRet: true
04-29 12:18:28.994  1389  1594 D GameManagerService: onLooperPrepared(), msg: MSG_APP_CREATE, pkgName: android
04-29 12:18:28.996  1389  4618 D FreecessController: Receive binder-module info(callerPid:0,uid:10096,code:0,interfaceToken:,flag:0) from freecessmonitor
04-29 12:18:28.997  1389  4483 W WindowManager: Exception in new application when starting activity android/com.android.internal.app.ResolverActivity
04-29 12:18:28.997  1389  4483 W WindowManager: android.os.TransactionTooLargeException: data parcel size 1283064 bytes
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:605)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2655)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1090)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded(RootWindowContainer.java:2308)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.RootWindowContainer.lambda$5fbF65VSmaJkPHxEhceOGTat7JE(Unknown Source:0)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.-$$Lambda$RootWindowContainer$5fbF65VSmaJkPHxEhceOGTat7JE.apply(Unknown Source:8)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:315)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.internal.util.function.pooled.OmniFunction.apply(OmniFunction.java:78)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:4260)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1396)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1388)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.RootWindowContainer.attachApplication(RootWindowContainer.java:2285)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:8421)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6573)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6661)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2759)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3570)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
04-29 12:18:28.997  1389  4483 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1159)
04-29 12:18:28.997  1389  4483 E ActivityManager: Exception thrown launching activities in ProcessRecord{71a2b36 6097:system:ui/1000}
04-29 12:18:28.997  1389  4483 E ActivityManager: android.os.TransactionTooLargeException: data parcel size 1283064 bytes
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.os.BinderProxy.transact(BinderProxy.java:605)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2655)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1090)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded(RootWindowContainer.java:2308)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.RootWindowContainer.lambda$5fbF65VSmaJkPHxEhceOGTat7JE(Unknown Source:0)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.-$$Lambda$RootWindowContainer$5fbF65VSmaJkPHxEhceOGTat7JE.apply(Unknown Source:8)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:315)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.internal.util.function.pooled.OmniFunction.apply(OmniFunction.java:78)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:4260)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1396)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1388)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.RootWindowContainer.attachApplication(RootWindowContainer.java:2285)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:8421)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6573)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6661)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2759)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3570)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
04-29 12:18:28.997  1389  4483 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:1159)
04-29 12:18:28.998  1389  4483 I ActivityManager: Killing 6097:system:ui/1000 (adj -10000): error during init
```

**Comment by Trysupe** [comment]
```
04-29 13:05:03.495  1389  4557 E ActivityTaskManager: Transaction too large, intent: Intent { act=android.intent.action.SEND typ=text/plain flg=0x800001 cmp=android/com.android.internal.app.ResolverActivity clip={text/plain {...}} (has extras) }, extras size: 535604, icicle size: 0
04-29 13:05:03.495  1389  4557 D PkgDataHelper: notifyAppCreate(), pkgName: android, sendRet: true
04-29 13:05:03.495  1389  1594 D GameManagerService: onLooperPrepared(), msg: MSG_APP_CREATE, pkgName: android
04-29 13:05:03.498  1389  4557 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1073768)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: Second failure launching android/com.android.internal.app.ResolverActivity, giving up
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: android.os.TransactionTooLargeException: data parcel size 1073768 bytes
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.os.BinderProxy.transact(BinderProxy.java:605)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2655)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1090)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded(RootWindowContainer.java:2308)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.RootWindowContainer.lambda$5fbF65VSmaJkPHxEhceOGTat7JE(Unknown Source:0)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.-$$Lambda$RootWindowContainer$5fbF65VSmaJkPHxEhceOGTat7JE.apply(Unknown Source:8)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:315)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.internal.util.function.pooled.OmniFunction.apply(OmniFunction.java:78)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:4260)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1396)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1388)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.RootWindowContainer.attachApplication(RootWindowContainer.java:2285)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:8421)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6573)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6661)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2759)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3570)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
04-29 13:05:03.498  1389  4557 E ActivityTaskManager: 	at android.os.Binder.execTransact(Binder.java:1159)
04-29 13:05:03.498  1389  4557 V WindowManager: Prepare app transition: transit=TRANSIT_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_ACTIVITY_OPEN alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:5766 com.android.server.wm.DisplayContent.prepareAppTransition:5760 com.android.server.wm.ActivityRecord.prepareActivityHideTransitionAnimation:3244 com.android.server.wm.ActivityRecord.finishIfPossible:3201 com.android.server.wm.ActivityRecord.finishIfPossible:3033 
04-29 13:05:03.498  1389  4557 W WindowManager: Execute app transition: mNextAppTransition=TRANSIT_ACTIVITY_OPEN, displayId: 0 Callers=com.android.server.wm.ActivityRecord.prepareActivityHideTransitionAnimation:3246 com.android.server.wm.ActivityRecord.finishIfPossible:3201 com.android.server.wm.ActivityRecord.finishIfPossible:3033 com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked:1122 com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded:2308 
04-29 13:05:03.501  1389  4557 D MARsPolicyManager: onPackageResumedFG pkgName = org.openhab.habdroid.beta, userId = 0
04-29 13:05:03.502  1389  4557 I SemDvfsHyPerManager: acquire hyper - AMS_ACT_RESUME/1389@20, type = -999
```

**Comment by mueller-ma** [comment]
If I read this correctly an exception is thrown, but not returned to the app. I don't think I can do anything here.

> Is the log resetted every time the app is (forcefully) closed and reopened?

I think there's a fixed maximum size of the log and a circular buffer, so it only keeps the last X log lines. There's a developer setting called "Logger buffer size" which represents this maximum size.
openHAB only clears the log when pressing the "clear log" button.

**Comment by Trysupe** [comment]
Does the openHAB Log have **all** android logs in it or only the openhab ones?

**Comment by mueller-ma** [comment]
Only openHAB ones.

**Comment by Trysupe** [comment]
> I don't think I can do anything here.

Shall we close this issue or leave it open?

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/6401513/mobile-foss-beta-debug.zip)

Do you see a message now if the log is too large to share?

**Comment by Trysupe** [comment]
> Do you see a message now if the log is too large to share?

Sadly not. For me it's the exact same behaviour than before

**Comment by mueller-ma** [comment]
No, not needed in this case. I guess there's nothing I can do to fix this.

**Comment by Trysupe** [comment]
I've sent this topic to samsung. **Maybe** there will be a bugfix in some update.
