### ISSUE TITLE
Material Design 3 TODO

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-android#3097]
In the MD3 update, a few places were forgotten/still need updating:
- The title of the chart scaling pref is not bold (or has wrong weight)
- The header of the NFC activity needs updating (title text color, maybe whole header should become a card or something)
- Notification list probably shouldn't have lines now
- Same for sitemap widget list?
- With the left side drawer now being rounded, it looks somewhat weird now that it doesn't span the room below the action bar

More generally, I'm not sure the MD3 update is a good idea in its present state, since for that to look good, quite a few additional updates are needed:
- Sitemap widgets need a bit of an overhaul, maybe using pills? But certainly different font sizes, similar to e.g. lists in the Google Drive app
- Sitemap widgets opening a dialog (e.g. selection) should open a bottom panel instead 
- List/activity background needs to use a system color (compare to Google apps) or keep our previous color theme

Thoughts?

**Comment by maniac103** [comment]
Maybe also move sliders and buttons below the text? Or also to a bottom panel?

**Comment by maniac103** [comment]
Could also use a collapsing top app bar for subpages in 1-pane layout.

**Comment by mueller-ma** [comment]
I fully agree with the "In the MD3 update, a few places were forgotten/still need updating" paragraph.

> Sitemap widgets need a bit of an overhaul, maybe using pills? But certainly different font sizes, similar to e.g. lists in the Google Drive app, and maybe show the value below the title in smaller size?

I personally don't use a lot of Google apps, except the apps that are part of the OS. The closest app of them to openHAB is the Android settings app. 
The items with switches show the value below the title and the switch on the right is spanning both lines. This should suit for openHAB as well. 

Can you share a screenshot with the mentioned pills?

> Sitemap widgets opening a dialog (setpoint, selection, map) should open a bottom panel instead

👍 

> List/activity background needs to use a system color (compare to Google apps) or keep our previous color theme

The base theme contains: `<item name="android:windowBackground">?android:colorBackground</item>`

So shouldn't the background color fit? `android:colorBackground` is overridden by a value that was created by https://m3.material.io/theme-builder#/custom



> Maybe also move sliders and buttons below the text? Or also to a bottom panel?

-1 from my side. I don't want to make two clicks until I can change a switch or a slider.


> Could also use a collapsing top app bar for subpages in 1-pane layout. Same for prefs, NFC (collapsing the full header) and notifications.

Also requested in #139. 


Thinking about the 1/2-pane layout: Maybe replace it by the behavior of Basic UI?

Some of the suggestions here will lead to more space required for sitemap widgets. Should we add some kind of "compact" mode for people that like to have the same amount items on one page as currently?

**Comment by maniac103** [comment]
> Some of the suggestions here will lead to more space required for sitemap widgets. Should we add some kind of "compact" mode for people that like to have the same amount items on one page as currently?

IMHO no. More (white) space being required is a side effect of MD3. Additionally, the sizing behavior (title vs. value vs. control) has been an endless source of discussion and issue reports, which is why I think we should tackle it when doing a redesign anyway.

> I don't want to make two clicks until I can change a switch or a slider.

The thing is that the MD3 multi-button is simply much larger than in the old design, and for being inlined in one line, it's just too large IMO. It's probably OK to just change the arrangement to be vertical, though: for the slider, one could place title on top and value + slider below it.

> The closest app of them to openHAB is the Android settings app.

Settings is mostly lists of prefs, which is why I don't think it's a good role model here. I'll share some screenshots of the Drive, Home and Family Link apps later.

**Comment by maniac103** [comment]
Here are the promised screenshots, showing various MD3 aspects:

1. Google Drive app file listing, showing the smaller fonts used generally
![drive](https://user-images.githubusercontent.com/781373/203048646-8296c775-6b4a-44ba-9c65-20ca41c3ed92.png)
2. Google Home, showing the generally larger amount of whitespace in lists
![home](https://user-images.githubusercontent.com/781373/203049783-9303324b-05ab-4c71-846b-4ddd2862079d.png)
3. Family Link, showing pills
![familylink](https://user-images.githubusercontent.com/781373/203049839-b763a394-ee5a-4c1d-a235-2c3966002f51.png)

1 and 3 also show the (wallpaper dependent) background color used by most of Google's apps (curiously not including Home).

**Comment by maniac103** [comment]
With that as guideline, I hacked around a bit today to show what I meant above.
To recap, current state is this:
![Screenshot_20221121_130002](https://user-images.githubusercontent.com/781373/203050413-d3649ec7-f76c-4f06-9d96-15df1133de59.png)

My current state is this:
![Screenshot_20221121_125800](https://user-images.githubusercontent.com/781373/203050592-60576e49-8087-4563-acad-60796535175a.png)
![Screenshot_20221121_125915](https://user-images.githubusercontent.com/781373/203050633-2ab626c5-59e5-4b2c-a7af-115d2e2d7e38.png)

Selection bottom sheet looks like this:
![Screenshot_20221121_125810](https://user-images.githubusercontent.com/781373/203050693-f3541fab-c866-4df5-8cdc-3c5240883b7d.png)

And setpoint bottom sheet like this:
![Screenshot_20221121_125823](https://user-images.githubusercontent.com/781373/203050713-7b2203d8-ab5b-4b2e-b757-e4d8b47a15d2.png)

Obviously paddings etc. are not yet finalized, I rather wanted to show the general direction I was heading at. Thoughts?

**Comment by mueller-ma** [comment]
> Maybe also move [...] buttons below the text? Or also to a bottom panel?

I see you were talking about switch items with mappings. These are indeed too large. 

Maybe keep the current behavior: Show the buttons to the right of the label. If it requires too much space, convert it to a selection widget. And maybe handle switches with mappings and selections the same?

I'm not sure if the slider in setpoint widgets is suitable for every use-case.

**Comment by maniac103** [comment]
> I'm not sure if the slider in setpoint widgets is suitable for every use-case.

What use cases does a `NumberPicker` possibly provide that a `Slider` doesn't?

> Maybe keep the current behavior: Show the buttons to the right of the label. If it requires too much space, convert it to a selection widget. And maybe handle switches with mappings and selections the same?

I don't like this magic behavior. The user already expressed the wish for a different UI, or he would not have put `Switch` instead of `Selection` (or vice versa) into his sitemap file. What's the advantage of taking away choice here?

**Comment by mueller-ma** [comment]
> What use cases does a NumberPicker possibly provide that a Slider doesn't?

Image you have 0 - 100 with a step size of 0.1. It might be quite hard to set the slider to one exact value, while you can enter the value by using the keyboard in `NumberPicker`.

> I don't like this magic behavior. The user already expressed the wish for a different UI, or he would not have put Switch instead of Selection (or vice versa) into his sitemap file. What's the advantage of taking away choice here?

At least the Switch -> Selection conversion is useful for me: I can define a Switch with mapping and don't have to care about all the different screen sizes of the devices that display sitemaps. If there's enough room, the buttons are displayed, otherwise it's converted to Selection.

**Comment by maniac103** [comment]
> Image you have 0 - 100 with a step size of 0.1. It might be quite hard to set the slider to one exact value, while you can enter the value by using the keyboard in NumberPicker.

That sounds like a quite contrived example...I was talking about real world use cases ;-) I imagine about 99% of the people just using it for controlling their heating, in which case neither a step size of 0.1 nor a range of 100 is needed. In fact, BasicUI does not even *have* any control besides the up and down buttons, which is another point suggesting we can change the UI rather feely there.
As a matter of fact, the NumberPicker control is both pretty old and (likely related) pretty ugly. It is not present in the MDC library, probably for a reason, so I don't think we should stick to it just for the sake of not changing anything.

> At least the Switch -> Selection conversion is useful for me

Maybe just do a compromise? Show N buttons (with N being somewhere between 6 and 8, and/or being a screen size dependent integer resource), and if more buttons are present, show another 'overflow' button (3 dots) which then opens the bottom sheet with radio buttons?

**Comment by mueller-ma** [comment]
Ok, sliders for setpoint and the overflow button for switches with mappings is fine.

**Comment by maniac103** [comment]
Some updates:

- Changed the frame item appearance
![Screenshot_20221125_125629](https://user-images.githubusercontent.com/781373/203981010-50770510-b519-4cc5-ba63-deaf20360cf0.png)
- Converted the item picker action select dialog to bottom sheet
![Screenshot_20221125_125754](https://user-images.githubusercontent.com/781373/203981252-89244ebd-956c-4def-b609-09281513505c.png)
- Section switches with too many items have the aforementioned overflow button now, which opens a selection bottom sheet

Code is here, if you want to play around with it (and maybe give feedback ;-) ): https://github.com/maniac103/openhab.android/tree/md3-redesign
I'll probably open a PR sometime next week.

**Comment by mueller-ma** [comment]
On the screenshots the bottom sheet in ItemPicker doesn't have rounded corners like them in the sitemap.

I'll have a look at the code soon.

**Comment by maniac103** [comment]
> On the screenshots the bottom sheet in ItemPicker doesn't have rounded corners like them in the sitemap

That happens when expanding the bottom sheet. Unexpended the corners are rounded, in expanded state they are not.

**Comment by mueller-ma** [comment]
Some comments on your code:

- In dark mode the Setpoint button that opens the bottom sheet is hardly visible (always black)
- Selection bottom sheet isn't closed after an item has been selected. Previously the dialog show closed.
- The brightness slider of Color items could always show it's value
- Frame items without text are just a white/black (depending on theme) gap. This could be removed if it's the first item on a page.
- The overflow button becomes selected when I press it, but it shouldn't, because the item state isn't "..."

By pressing the "open bottom sheet" button of a setpoint item I was able to crash the app, but cannot really reproduce the bug:
````
FATAL EXCEPTION: main
Process: org.openhab.habdroid, PID: 17901
java.lang.IllegalStateException: Fragment WidgetListFragment{34a5746} (e7ef568d-06fc-4485-b5a1-ac0b8c15d0dd) [url=https://..., title=...] has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1094)
	at org.openhab.habdroid.ui.WidgetListFragment.showBottomSheet(WidgetListFragment.kt:205)
	at org.openhab.habdroid.ui.WidgetAdapter$SetpointViewHolder.openSelection(WidgetAdapter.kt:878)
	at org.openhab.habdroid.ui.WidgetAdapter$SetpointViewHolder._init_$lambda$1(WidgetAdapter.kt:862)
	at org.openhab.habdroid.ui.WidgetAdapter$SetpointViewHolder.$r8$lambda$oAqOBp0I1zGmOIY0zmPSOoMn938(Unknown Source:0)
	at org.openhab.habdroid.ui.WidgetAdapter$SetpointViewHolder$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
````

**Comment by maniac103** [comment]
> - In dark mode the Setpoint button that opens the bottom sheet is hardly visible (always black)
> - Selection bottom sheet isn't closed after an item has been selected. Previously the dialog show closed.
> - The overflow button becomes selected when I press it, but it shouldn't, because the item state isn't "..."

Those 3 are now fixed.

> - Frame items without text are just a white/black (depending on theme) gap. This could be removed if it's the first item on a page.

Fixed (I hope)

> - The brightness slider of Color items could always show it's value

What exactly do you mean here? Set the label to be always visible (as per [here](https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md#user-content-addingremoving-the-value-label))?

> By pressing the "open bottom sheet" button of a setpoint item I was able to crash the app, but cannot really reproduce the bug:

I saw this (rarely) as well, but can't make sense of that yet, since the widget list fragment clearly *is* attached (it's visible after all). Need to investigate at some point.

**Comment by mueller-ma** [comment]
> Set the label to be always visible (as per [here](https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md#user-content-addingremoving-the-value-label))?

Yes

**Comment by maniac103** [comment]
>> By pressing the "open bottom sheet" button of a setpoint item I was able to crash the app, but cannot really reproduce the bug:
>
> I saw this (rarely) as well, but can't make sense of that yet, since the widget list fragment clearly is attached (it's visible after all). Need to investigate at some point.

Looks like the reproduction steps for this are
- go to subpage, open bottom sheet -> works
- go back
- enter subpage again, open bottom sheet again -> crash

I'll check this.
