### ISSUE TITLE
3.1.2-beta crashes instantly on sitemap with Dynamic color scheme selected

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#3214]
### Actual behaviour
Version 3.1.2-beta reproducibly crashes after selecting Dynamic color scheme and getting back to sitemap

### Expected behaviour
After selecting Dynamic color scheme, setting should be changed alike, sitemap then shown in that scheme, as it worked in ealier betas, when this setting was separate.
 
### Steps to reproduce
1. install 3.1.2-beta, start it
2. opens on preferred sitemap, might appear in "Default" scheme (I have "black" Design selected)
3. get to settings
4. see new Color scheme selector, select "Dymamic"
5. app will allow the change, show in settings
6. get out of settings by arrow on top left corner
7. crash. App disappears from screen.
8. Restart of app not possible, crashes instantly on opening (specific sitemap selected for opening)
9. re-install that version from github
10. start app from home screen, app opens with Default color scheme, you can loop back to #3 above ;-)
- log is wiped on crash
- other 2 schemes "Default" + "Basic UI" work well
- luckily, on install scheme is reset to Default, otherwise I guess it would require uninstall/install + full re-configuration
- Is the crash reported back to you? On repetitive crash, Android suggests so.

#### Client
* Android version: 13
* Device model: Samsung Galaxy S21
* App version : 3.1.2-beta
* Build flavor : Full
* Device language: DE

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

**Comment by mueller-ma** [comment]
Crash reported by Firebase:

```
Fatal Exception: java.lang.NullPointerException: tv.string must not be null
       at org.openhab.habdroid.util.ExtensionFuncsKt.getChartTheme(ExtensionFuncs.kt:449)
       at org.openhab.habdroid.ui.WidgetAdapter.<init>(WidgetAdapter.kt:106)
       at org.openhab.habdroid.ui.WidgetListFragment.onViewCreated(WidgetListFragment.kt:132)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by maniac103** [comment]
Damn, you beat me to it ;-) Will check this.
