### ISSUE TITLE
Crash inside Google Maps

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3237]
Maybe catch and ignore this issue as it's only on `onPause()`?

````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.br.w()' on a null object reference
       at com.google.maps.api.android.lib6.impl.cw.i(cw.java)
       at com.google.android.gms.maps.internal.q.bb(q.java:17)
       at fm.onTransact(fm.java:4)
       at android.os.Binder.transact(Binder.java:921)
       at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
       at com.google.android.gms.maps.internal.zzl.onPause(com.google.android.gms:play-services-maps@@18.1.0:2)
       at com.google.android.gms.maps.zzag.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
       at com.google.android.gms.dynamic.DeferredLifecycleHelper.onPause(com.google.android.gms:play-services-base@@18.0.1:1)
       at com.google.android.gms.maps.MapView.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
       at org.openhab.habdroid.ui.MapBottomSheet.onPause(MapViewHelper.kt:175)
       at androidx.fragment.app.Fragment.performPause(Fragment.java:3305)
       at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
````

**Comment by mueller-ma** [comment]
Crash happened 218 times for 65 users so far.

**Comment by maniac103** [comment]
Sounds like it shouldn't be hard to reproduce then. I'll check it. Need to figure out how to set up Google Maps API key etc. first though.
