### ISSUE TITLE
Notifications list crashes the beta app

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#3291]
### Actual behaviour
On call of Notifications in menu, app instantly crashes. Android suggests to cleen the cache, didn't help. Released app doesn't show this issue. Other menu items work as expected.
Happens both on Wifi and mobile networks.

### Expected behaviour
Notifications menu should show list of past push notifications.

 
### Steps to reproduce
1. open beta app (at least 3.3.2-beta and 3.3.3-beta)
2. select "Notifications" ("Benachrichtigungen") from main app menu

### Can you reproduce the issue in demo mode?
Yes

#### Client
* Android version: 13
* Device model: Samsung Galaxy S23
* App version : 3.3.3-beta
* Build flavor : Full
* Device language: DE

#### Server
* Server version: 3.4.2
* Reverse Proxy: 
* Authentication method : none

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* openHAB Cloud version : 
* Authentication method : user/pw

#### App log
<details>
  <summary>Click to expand</summary>

```
--------- beginning of crash
03-03 13:42:10.380  6537  6537 E AndroidRuntime: FATAL EXCEPTION: main
03-03 13:42:10.380  6537  6537 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 6537
03-03 13:42:10.380  6537  6537 E AndroidRuntime: java.lang.IllegalStateException: Fragment CloudNotificationListFragment{53d4870} (0c01c46a-e539-4be3-a037-23cd0eb6fdc0 id=0x7f0a00a1) not attached to a context.
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.fragment.app.Fragment.getString(Fragment.java:1066)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.CloudNotificationListFragment.getTitle(CloudNotificationListFragment.kt:191)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.activity.ContentController.getCurrentTitle(ContentController.kt:107)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.MainActivity.updateTitle(MainActivity.kt:1262)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.activity.ContentController.showTemporaryPage(ContentController.kt:574)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.activity.ContentController.openNotifications(ContentController.kt:385)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.MainActivity.openNotifications(MainActivity.kt:1242)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.MainActivity.setupDrawer$lambda$15(MainActivity.kt:902)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.MainActivity.$r8$lambda$FzMDGTifnIQDaIOBC7zbhF7qFY4(MainActivity.kt:0)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at org.openhab.habdroid.ui.MainActivity$$ExternalSyntheticLambda6.onNavigationItemSelected(R8$$SyntheticClass:0)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:303)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:494)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.view.View.performClick(View.java:7892)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.view.View.performClickInternal(View.java:7869)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.view.View$PerformClick.run(View.java:30880)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:226)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.os.Looper.loop(Looper.java:313)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8747)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
03-03 13:42:10.380  6537  6537 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
--------- beginning of main
03-03 13:42:12.984  9447  9447 E b.habdroid.beta: Not starting debugger since process cannot load the jdwp agent.
03-03 13:42:13.183  9447  9447 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
```

</details>

**Comment by maniac103** [comment]
Fallout of #3275, should do `context.getString()` [here](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt#L191).
