### ISSUE TITLE
Latest PlayStore Update 1.8.0.7 causes SSL client handshake error

### ISSUE THREAD

**Issue by StefanBertels** [openhab/openhab-android#332]
previous versions worked fine, Setup didn't change.

error message:
ssl handshake fehlgeschlagen, Sie brauchen vielleicht ein gültiges Client Zertifikat

Setup: 
openhab 1.9
user+pass set in app
NO client cert
self-signed server cert
self-created root cert installed on Android so openHAB can verify this

openHAB app links to this EMPTY how-to:
https://github.com/openhab/openhab.android/blob/master/KeyAuth.md

**Comment by mueller-ma** [comment]
Does the CN match the URL?
I opened #333 for the how-to

**Comment by StefanBertels** [comment]
Yes. CN matches, certificate itself should be ok. But chrome complains about the weak cert (sha1rsa).
OpenHAB worked fine with this certificate before (without those unsecure options to ignore cert name / cert security).

**Comment by StefanBertels** [comment]
Enabling "Ignoriere SSL-Zertifikat" (ignore ssl cert) helps. 
I tried to setup nginx reverse proxy as described in OpenHAB2 docs but it seems this doesn't work together with OpenHAB 1.x (I get some openhab error / java stacktrace).

**Comment by StefanBertels** [comment]
Error with my nginx proxy experiment (just http, openhab 1.x):

----

HTTP ERROR 500

Problem accessing /openhab.app. Reason:

    Server Error
Caused by:

java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:756)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:704)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:690)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:644)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators$8.hasNext(Iterators.java:777)
	at com.google.common.collect.Lists.newArrayList(Lists.java:138)
	at com.google.common.collect.Lists.newArrayList(Lists.java:119)
	at org.openhab.model.core.internal.ModelRepositoryImpl.getAllModelNamesOfType(ModelRepositoryImpl.java:135)
	at org.openhab.ui.internal.items.GenericItemUIProvider.getItem(GenericItemUIProvider.java:49)
	at org.openhab.ui.internal.items.GenericItemUIProvider.getLabel(GenericItemUIProvider.java:35)
	at org.openhab.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:143)
	at org.openhab.ui.internal.items.ItemUIRegistryImpl.getLabelFromWidget(ItemUIRegistryImpl.java:308)
	at org.openhab.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:222)
	at org.openhab.ui.webapp.internal.render.AbstractWidgetRenderer.getLabel(AbstractWidgetRenderer.java:114)
	at org.openhab.ui.webapp.internal.render.GroupRenderer.renderWidget(GroupRenderer.java:43)
	at org.openhab.ui.webapp.internal.render.PageRenderer.renderWidget(PageRenderer.java:158)
	at org.openhab.ui.webapp.internal.render.PageRenderer.processChildren(PageRenderer.java:121)
	at org.openhab.ui.webapp.internal.render.PageRenderer.processChildren(PageRenderer.java:138)
	at org.openhab.ui.webapp.internal.render.PageRenderer.processPage(PageRenderer.java:86)
	at org.openhab.ui.webapp.internal.servlet.WebAppServlet.service(WebAppServlet.java:127)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:350)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Thread.java:745)

**Comment by digitaldan** [comment]
Hi @StefanBertels , just trying to understand your issue, can you clarify a few things? 

>self-created root cert installed on Android so openHAB can verify this

>user+pass set in app
>NO client cert

I'm a little confused, so you had client based authentication using  a client based cert working, or no?  I'm not sure I understand you setup.  Are you connecting directly to OH or using a nginx proxy? Are you using client key auth, credentials or both?

>Enabling "Ignoriere SSL-Zertifikat" (ignore ssl cert) helps.

When you says helps, do you mean you no longer have the issue? Or is something still not working?

>Error with my nginx proxy experiment (just http, openhab 1.x):

I'm not sure i understand what you are trying to do?

**Comment by mueller-ma** [comment]
> 
> 
>     Enabling "Ignoriere SSL-Zertifikat" (ignore ssl cert) helps.
> 
> When you says helps, do you mean you no longer have the issue? Or is something still not working?

This is still an issue since enabling this option is unsecure #314

**Comment by StefanBertels** [comment]
@digitaldan:

No, I don't have client certificates. I have a server certificate. 
Server certificate is installed into jetty. This setup is plain OpenHAB 1.x without any proxy.

I have credentials (user+pass) set in OpenHAB app.

Regarding nginx: I just tried to setup access for OpenHAB the proxy way -- as documented for OpenHAB 2.x. If this had worked I would have disabled https in jetty so nginx would access a unsecured local OpenHAB API (http, no credentials neccessary within LAN). But his didn't work out (see error message).

@mueller-ma:

Exactly. This option is unsafe so I'm looking for ways to make https secure again.

**Comment by lolodomo** [comment]
On my side, I have no reverse proxy installed, I am just using a HTTPS local URL. Since version 1.8.0.7, I get the error "SSL handshake failed - maybe you need a valid client certificate.
The working workaround for me is to check the option "Ignore SSL certificate".
It was not required with the previous version. Is it normal ?

**Comment by digitaldan** [comment]
> Since version 1.8.0.7, I get the error "SSL handshake failed - maybe you need a valid client certificate.

Are you using local discovery or have you entered your local OH address in?  Are you using a real SSL cert or one that OH generates?  If it is one that is generated, then I think you should get the error even with the previous version.

I have noticed that with local discovery we get this error now where before we did not, I'm not sure if we use to default to the local http vs https port , or if SSL validity was somehow ignored locally, which is why maybe @lolodomo you did not get this prompt before ( but should have imho).

**Comment by digitaldan** [comment]
>I have a server certificate. Server certificate is installed into jetty.

Ok, this is more clear, we have also mentioned https://github.com/openhab/openhab.android/blob/master/KeyAuth.md in this thread which is not related to your issue since you not using client authentication, yes?

@StefanBertels So it looks like our new https stack is not reading something with user supplied server/root cert chains, that is indeed an issue, we should not need to allow all untrusted certs in this case. 
 
I have also heard that we may have this same error if the server is using a depreciated encryption scheme/cipher.  So I'm not sure if this is one issue or more.

>This is still an issue since enabling this option is unsecure #314

Yes i understand that, I was asking @StefanBertels to clarify about his situation specifically.

**Comment by digitaldan** [comment]
@rusitschka could also help out here?

**Comment by lolodomo** [comment]
In my case, both locale and remote URL are set with HTTPS. The remote URL is myopenhab and it works well. My licale URL looks like https://192.168.xx.xxx:8443 with default certificate produced by OH. In this case, I get the error if I don't check the options "ignore certificate" and "ignore domaon SSL".

**Comment by digitaldan** [comment]
>, I get the error if I don't check the options "ignore certificate" and "ignore domaon SSL".

The certs generated by OH are obviously not signed by a know authority.  I'm not sure how this was working before, but its not a great experience for sure.   

I think the best way (and maybe this was mentioned) would be to remove the ignore option from the settings and prompt the user on unknown certs to accept permanently or reject the certificate.  This will require a fair bit of code rework.

**Comment by StefanBertels** [comment]
My setup was trusted (on my Android devices):
I created my own root CA cert and installed this on my android device.
I created my own certificate for OpenHAB and used my root CA to sign it.
I installed this OpenHAB certificate into jetty.

The certificate matches fqdn, it has some alternative name (so I can use another hostname without cert errors / full security).

Some days ago everything was fine, so I think the problem came with latest OpenHAB app update.

I checked the certificate -- not expired. I have another phone -- same issue.

**Comment by snoekieboe** [comment]
Running into the exact same issue since upgrading my andriod openhab to version 1.8.0.7. Any workarounds available to get this working in the meantime?

Br

**Comment by sumnerboy12** [comment]
Also seeing this issue, running OH v1.8.3 with a LetsEncrypt cert for my personal domain (i.e. a valid cert). Was working fine prior to the latest Habdroid update. Only way to connect is to tick the "Ignore SSL cert" option.

**Comment by snoekieboe** [comment]
In my case even tapping "Ignoe SSL cert"  does not seem to make a difference. 
it does make the local HTTPS connection work.. but my myopenhabcloud remote https connection still fails.

**Comment by TheNetStriker** [comment]
My client certificate also doesn't work anymore since the update. I didn't change anything on my firewall or the certificate and it is valid until 14.12.2064. Setting the "Ignoe SSL cert" also didn't help.

**Comment by mueller-ma** [comment]
We're using MTM to allow invalid certificates during handshake. Please reopen if you have any issues.
