### ISSUE TITLE
Crash due to a memory leak

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#546]
```
12-20 18:46:06.766 16131-16187/org.openhab.habdroid W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
12-20 18:46:06.766 16131-16187/org.openhab.habdroid E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
12-20 18:46:07.155 16131-16146/org.openhab.habdroid I/art: Background sticky concurrent mark sweep GC freed 76772(5MB) AllocSpace objects, 0(0B) LOS objects, 24% free, 15MB/20MB, paused 22.126ms total 123.484ms
12-20 18:46:08.294 16131-16146/org.openhab.habdroid I/art: Background partial concurrent mark sweep GC freed 125200(5MB) AllocSpace objects, 1(2MB) LOS objects, 39% free, 13MB/21MB, paused 22.361ms total 144.535ms
12-20 18:46:10.160 16131-16146/org.openhab.habdroid I/art: Background sticky concurrent mark sweep GC freed 186887(8MB) AllocSpace objects, 0(0B) LOS objects, 37% free, 13MB/21MB, paused 21.330ms total 136.719ms
12-20 18:46:12.023 16131-16146/org.openhab.habdroid I/art: Background partial concurrent mark sweep GC freed 175342(7MB) AllocSpace objects, 0(0B) LOS objects, 39% free, 13MB/21MB, paused 21.343ms total 155.321ms
12-20 18:46:12.028 16131-16187/org.openhab.habdroid E/CrashlyticsCore: Failed to write session file for session ID: 5A3AA0EA027F-0001-3F03-2BAB46ABA736
                                                                       java.io.FileNotFoundException: /data/data/org.openhab.habdroid/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/5A3AA0EA027F-0001-3F03-2BAB46ABA736BeginSession.cls: open failed: EMFILE (Too many open files)
                                                                           at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                           at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                           at com.crashlytics.android.core.CrashlyticsController.writeToCosFromFile(CrashlyticsController.java:1438)
                                                                           at com.crashlytics.android.core.CrashlyticsController.synthesizeSessionFile(CrashlyticsController.java:1351)
                                                                           at com.crashlytics.android.core.CrashlyticsController.writeSessionPartsToSessionFile(CrashlyticsController.java:1320)
                                                                           at com.crashlytics.android.core.CrashlyticsController.closeOpenSessions(CrashlyticsController.java:594)
                                                                           at com.crashlytics.android.core.CrashlyticsController.doCloseSessions(CrashlyticsController.java:576)
                                                                           at com.crashlytics.android.core.CrashlyticsController.doCloseSessions(CrashlyticsController.java:544)
                                                                           at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:324)
                                                                           at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:311)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
                                                                           at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: android.system.ErrnoException: open failed: EMFILE (Too many open files)
                                                                           at libcore.io.Posix.open(Native Method)
                                                                           at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                           at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                           at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.writeToCosFromFile(CrashlyticsController.java:1438) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.synthesizeSessionFile(CrashlyticsController.java:1351) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.writeSessionPartsToSessionFile(CrashlyticsController.java:1320) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.closeOpenSessions(CrashlyticsController.java:594) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.doCloseSessions(CrashlyticsController.java:576) 
                                                                           at com.crashlytics.android.core.CrashlyticsController.doCloseSessions(CrashlyticsController.java:544) 
                                                                           at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:324) 
                                                                           at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:311) 
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75) 
                                                                           at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
12-20 18:46:12.048 16131-16214/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-3
                                                                      Process: org.openhab.habdroid, PID: 16131
                                                                      java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                          at java.lang.Thread.nativeCreate(Native Method)
                                                                          at java.lang.Thread.start(Thread.java:1063)
                                                                          at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
                                                                          at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
12-20 18:46:12.076 16131-16195/org.openhab.habdroid E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
```

**Comment by digitaldan** [comment]
>12-20 18:46:06.766 16131-16187/org.openhab.habdroid W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory

>12-20 18:46:06.766 16131-16187/org.openhab.habdroid E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                          at java.lang.Thread.nativeCreate(Native Method)

> Caused by: android.system.ErrnoException: open failed: EMFILE (Too many open files)

Our app ran out of memory and could not create anymore file pointers, and so crashalytics could not get to its own files, but the the root cause is a memory leak, not crashalytics.

when Java runs out of memory, random parts of the app will crash, including our crash reporting.
