### ISSUE TITLE
Crash when clicking on "Got it!" in the refresh snackbar

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#707]
Steps to reproduce:
1. Go to a subpage
2. Refresh
3. Go back
4. Click "Got it!"

```
02-07 15:00:20.386 1066-1066/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.openhab.habdroid, PID: 1066
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:498)
                                                                        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:487)
                                                                        at org.openhab.habdroid.ui.OpenHABWidgetListFragment$3.onClick(OpenHABWidgetListFragment.java:254)
                                                                        at android.support.design.widget.Snackbar$1.onClick(Snackbar.java:255)
                                                                        at android.view.View.performClick(View.java:5637)
                                                                        at android.view.View$PerformClick.run(View.java:22433)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

@FlorianSW

**Comment by maniac103** [comment]
Should either remove the snackbar when going back, or use `v.getContext()` as context in line 254.
