### ISSUE TITLE
Crash when wifi got disabled while app was in background

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#752]
### Actual behaviour
Shouldn't crash

### Expected behaviour
Crashes, see below

 
### Steps to reproduce
1. Open App when wifi is enabled
2. Bring app in background (but don't close it)
3. Disable wifi
4. Open App again

### Can you reproduce the issue in demo mode?

Yes

#### Client
* Android version: 7.1.2
* Device model: Oneplus X
* Stock or customized ROM: LineageOS 14.1
* App version :  2.0.18
* Build flavor : foss
* Device language: EN

#### App log
```
03-08 13:18:30.802 32750-300/org.openhab.habdroid E/ConnectionFactory: Network is not available
03-08 13:18:30.804 32750-32750/org.openhab.habdroid D/OpenHABMainActivity: Remote URL, username or password are empty, no GCM registration will be made
03-08 13:18:30.813 32750-32750/org.openhab.habdroid D/OpenHABMainActivity: Remote URL, username or password are empty, no GCM registration will be made
03-08 13:18:30.824 32750-32750/org.openhab.habdroid D/OpenHABDrawerAdapter: No count label
03-08 13:18:30.833 32750-32750/org.openhab.habdroid D/AndroidRuntime: Shutting down VM
03-08 13:18:30.834 32750-32750/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.openhab.habdroid, PID: 32750
                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.openhab.habdroid.core.connection.Connection.getOpenHABUrl()' on a null object reference
                                                                          at org.openhab.habdroid.ui.drawer.OpenHABDrawerAdapter.getView(OpenHABDrawerAdapter.java:102)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2378)
                                                                          at android.widget.ListView.makeAndAddView(ListView.java:1970)
                                                                          at android.widget.ListView.fillDown(ListView.java:704)
                                                                          at android.widget.ListView.fillFromTop(ListView.java:765)
                                                                          at android.widget.ListView.layoutChildren(ListView.java:1716)
                                                                          at android.widget.AbsListView.onLayout(AbsListView.java:2170)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1196)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                          at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
                                                                          at android.view.View.layout(View.java:17641)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by maniac103** [comment]
#688 likely will have fixed this as well.

**Comment by mueller-ma** [comment]
Yes, seems to be fixed
