### ISSUE TITLE
Crash on RTL languages

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#758]
### Steps to reproduce
1. Change device language to (XB) ...
2. Start app
3. App crashes
4. Change language back to LTR
5. App workes

### Can you reproduce the issue in demo mode?

Yes

#### Client
* Android version: 5.1.1
* Device model: Fire Tablet 8
* Stock or customized ROM: Custom
* App version : c183aa107cdff0cdf27f530aaedfef02297a6dec
* Build flavor : foss

#### App log
```
03-08 18:13:14.875 23964-23964/org.openhab.habdroid A/OpenHABMainActivity: Could not instantiate activity controller class '‏‮org.openhab.habdroid.ui.activity.ContentControllerTwoPane‬‏'
03-08 18:13:14.879 23964-23964/org.openhab.habdroid D/AndroidRuntime: Shutting down VM
03-08 18:13:14.881 23964-23964/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.openhab.habdroid, PID: 23964
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openhab.habdroid/org.openhab.habdroid.ui.OpenHABMainActivity}: java.lang.RuntimeException: java.lang.ClassNotFoundException: Invalid name: ‏‮org.openhab.habdroid.ui.activity.ContentControllerTwoPane‬‏
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                          at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:151)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                       Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Invalid name: ‏‮org.openhab.habdroid.ui.activity.ContentControllerTwoPane‬‏
                                                                          at org.openhab.habdroid.ui.OpenHABMainActivity.onCreate(OpenHABMainActivity.java:310)
                                                                          at android.app.Activity.performCreate(Activity.java:5990)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                          at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                       Caused by: java.lang.ClassNotFoundException: Invalid name: ‏‮org.openhab.habdroid.ui.activity.ContentControllerTwoPane‬‏
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.Class.forName(Class.java:309)
                                                                          at java.lang.Class.forName(Class.java:273)
                                                                          at org.openhab.habdroid.ui.OpenHABMainActivity.onCreate(OpenHABMainActivity.java:304)
                                                                          at android.app.Activity.performCreate(Activity.java:5990) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                          at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by mueller-ma** [comment]
Note: (XB) and some chars I don't have on my keyboard is actually English in RTL.

**Comment by maniac103** [comment]
Can you try whether making the controller_class translatable="false" fixes the issue? I think it's not a problem of RTL itself, but of the way the XB locale works.

**Comment by mueller-ma** [comment]
No, that doesn't fix the issue.

**Comment by maniac103** [comment]
https://www.thedroidsonroids.com/blog/testing-android-apps-pseudolocalization suggests it should help though. Did you catch both instances of the string resource, and did you rebuild/clean build after the change?

**Comment by mueller-ma** [comment]
I guess it doesnt work as it isn't `<string>`, it's `<item name="controller_class" type="string"`.

**Comment by maniac103** [comment]
Then we probably should make it a string ;-)
