### ISSUE TITLE
Crash when selection client cert

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#802]
### Actual behaviour
App crashes when I want to select a client certificate.

#### Client
* Android version: 7.1.2
* Device model: Oneplus X
* Stock or customized ROM: LineageOS 14.1
* App version : 2.0.32
* Build flavor : foss
* Device language: DE

#### App log
```
03-24 15:32:41.572 19483-19483/org.openhab.habdroid.beta E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: org.openhab.habdroid.beta, PID: 19483
                                                                           java.lang.NullPointerException: uriString
                                                                               at android.net.Uri$StringUri.<init>(Uri.java:475)
                                                                               at android.net.Uri$StringUri.<init>(Uri.java)
                                                                               at android.net.Uri.parse(Uri.java:437)
                                                                               at org.openhab.habdroid.ui.OpenHABPreferencesActivity$SslSettingsFragment$2.onPreferenceClick(OpenHABPreferencesActivity.java:341)
                                                                               at android.preference.Preference.performClick(Preference.java:999)
                                                                               at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
                                                                               at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                               at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
                                                                               at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
                                                                               at android.widget.AbsListView$3.run(AbsListView.java:4054)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by slawekjaranowski** [comment]
Error occurs because you don't set remote url.
Please first set remote url.

Maybe application should check if remote url is set correctly before this option.

**Comment by maniac103** [comment]
> Maybe application should check if remote url is set correctly before this option.

Not maybe, it must do that, as the client cert stuff is also used for local connections.
