### ISSUE TITLE
Version 2.0.31 crashes when loading a mapping

### ISSUE THREAD

**Issue by TheChrissi1** [openhab/openhab-android#823]
So i've got the problem that the app crashes when it loads mappings.
If i don't scroll down to the specific Item in the sitemap with the mapping the app works perfectly fine. 

When i choose a sitemap without a mapping i can scroll all the way down to the bottom without crashing the app.

I'm using the openhab-android-2.0.31-release.
Android Version: 4.4.2

This is the switch that brings the app to crash:
Switch item=TEXTALARMKEYPAD label="" icon="none" mappings=[1="1", 2="2", 3="3"]

I did not change one line in the code.

This is the error in Android Studio:
```
4-04 18:35:15.259 3173-3173/org.openhab.habdroid.beta E/InputEventReceiver: Exception dispatching input event.
04-04 18:35:15.259 3173-3173/org.openhab.habdroid.beta W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x416e3e18)
04-04 18:35:15.259 3173-3255/org.openhab.habdroid.beta I/MyWebImage: Cache for http://192.168.1.15:8080/icon/none?state=10&format=PNG is empty, getting image
04-04 18:35:15.359 3173-3173/org.openhab.habdroid.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openhab.habdroid.beta, PID: 3173
    android.view.InflateException: Binary XML file line #0: Error inflating class org.openhab.habdroid.ui.widget.SegmentedControlButton
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at org.openhab.habdroid.ui.OpenHABWidgetAdapter$SectionSwitchViewHolder.bind(OpenHABWidgetAdapter.java:680)
        at org.openhab.habdroid.ui.OpenHABWidgetAdapter.onBindViewHolder(OpenHABWidgetAdapter.java:200)
        at org.openhab.habdroid.ui.OpenHABWidgetAdapter.onBindViewHolder(OpenHABWidgetAdapter.java:76)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1330)
        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1074)
        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1758)
        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2970)
        at android.view.View.dispatchTouchEvent(View.java:7811)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2169)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1613)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2539)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
    	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.

```

**Comment by maniac103** [comment]
@TheChrissi1 Can we get the full logcat, in particular the 'caused by' parts of the crash stacktrace?
