### ISSUE TITLE
Crash on network change if app is in background on API 24+

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-android#953]
### Actual behaviour
The app crashes if it's in background, the network changes (e.g. Wifi drops out) and it's running on a device running Android Oreo or newer.

### Expected behaviour
App shouldn't crash

 
### Steps to reproduce
See above.

### Can you reproduce the issue in demo mode?
Crash is unrelated to connected server

#### Client
* Android version: 8.1
* Device model: Oppo R7 Plus
* Stock or customized ROM: LineageOS 15.1
* App version : 2.2.10 beta
* Build flavor : Full
* Device language: DE

#### App log
```
07-16 21:52:15.579 W/ActivityManager(21878): Background start not allowed: service Intent { act=org.openhab.habdroid.action.REGISTER_GCM cmp=org.openhab.habdroid/.core.GcmRegistrationService } to org.openhab.habdroid/.core.GcmRegistrationService from pid=15396 uid=10214 pkg=org.openhab.habdroid
07-16 21:52:15.583 D/AndroidRuntime(15396): Shutting down VM
07-16 21:52:15.587 E/AndroidRuntime(15396): FATAL EXCEPTION: main
07-16 21:52:15.587 E/AndroidRuntime(15396): Process: org.openhab.habdroid, PID: 15396
07-16 21:52:15.587 E/AndroidRuntime(15396): java.lang.IllegalStateException: Not allowed to start service Intent { act=org.openhab.habdroid.action.REGISTER_GCM cmp=org.openhab.habdroid/.core.GcmRegistrationService }: app is in background uid UidRecord{15ba96b u0a214 RCVR idle change:uncached procs:1 seq(0,0,0)}
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.CloudMessagingHelper.onConnectionUpdated(CloudMessagingHelper.java:30)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.connection.ConnectionFactory.handleCloudCheckDone(ConnectionFactory.java:444)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.connection.ConnectionFactory.handleMessage(ConnectionFactory.java:304)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.os.Looper.loop(Looper.java:164)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by maniac103** [comment]
Found an easy solution, the support library already has everything in place.

**Comment by mueller-ma** [comment]
Sadly I don't have a physical device with Android 8 and testing this with an emulator doesn't seem to make sense.

**Comment by maniac103** [comment]
I wrote `API < 26` ;-) I only have Android 8 myself, can't test on older versions.

**Comment by mueller-ma** [comment]
:man_facepalming: I'll test this soon
